### ISSUE TITLE
Convert to python3

### ISSUE THREAD

**Issue by paalbra** [FortyNorthSecurity/EyeWitness#283]
Python 2.x is going away. If EyeWitness is going to live on, the code base needs to be converted to python3 eventually.

An issue here might be external dependencies that might not be available/easily converted.

**Comment by t3ntman** [comment]
Agreed, needs converted to Python 3 ;)

**Comment by Raikia** [comment]
+1 THIS IS A MISSION CRITICAL ISSUE TRUNCER

**Comment by xvicsagex** [comment]
+1 trolling

**Comment by ChrisTruncer** [comment]
@paalbra - This is an area for providing issues, such as a crash in the codebase vs. more so suggestions. When people come with suggestions, I generally suggest to go ahead and also include a pull request with the suggestion. However, this suggestion really takes the cake for being something that's not really actionable.

This is like telling metasploit to upgrade their version of Ruby. I don't know if you have an understanding of the undertaking that doing this suggestion would required. Additionally you even state that external dependencies might be an issue. Submitting a "suggestion" without even researching the feasibility of it can be frustrating from a developers perspective.

Open source devs are people that have day jobs, families, personal interests, and more. Suggesting something like this if anything makes a developer not want to help. Please try to think about suggestions prior to submitting them, and if you still feel the need to submit a suggestion, provide a pull request as well.

**Comment by rhertzog** [comment]
Can we reopen this issue please? python will stop being officially supported at the end of this year so python 2 code is actively removed from Linux distribution such as Debian Testing and this is affecting Kali where we would prefer to keep eyewitness but for that to happen someone must do the work of updating the codebase to work with Python 3.

A large number of Python libraries are now available for Python 3 and if some are missing, here would be a good place to track the list of problematic dependencies that need to be fixed first.

(This is tracked in Kali here: https://gitlab.com/kalilinux/packages/eyewitness/issues/1)

**Comment by rhertzog** [comment]
From a quick check in Kali, here's the status for the various dependencies:

- [x] bs4
- [x] fuzzywuzzy
- [x] levenshtein
- [x] netaddr
- [x] openssl
- [x] PIL
- [x] pyasn1
- [x] pyvirtualdisplay
- [ ] qt4 -> needs to swich to Qt5
- [ ] rdpy: see https://github.com/citronneur/rdpy/issues/91
- [x] rsa
- [x] selenium
- [x] service-identity
- [x] pytesseract
- [x] twisted

So Qt and rdpy are the only real blockers.

**Comment by ChrisTruncer** [comment]
This can now be closed :)

The latest version does support Python 3 (@rhertzog). The only issue is it cannot screenshot RDP or VNC due to rdpy not currently being updated to python3.

**Comment by rhertzog** [comment]
@ChrisTruncer Thanks! But it looks like you typoed the version number. It's "3.o" instead of the expected "3.0" (i.e. it's letter "o" instead of figure "0"). Can you fix the tag name?

**Comment by rhertzog** [comment]
@ChrisTruncer Another quick question. What's the status wrt QT5 support (#301)?

AFAIK there's no Python 3 module for QT4 so I guess you must have removed something. But looking at setup.sh I still see "apt install python-qt4", I wonder why... and I also see a new "pip install python_qt_binding" in some places, where is that used? I can't find any trace of it in the code.

**Comment by ChrisTruncer** [comment]
you're correct @rhertzog - I just fixed the qt4 issues and drafted a new release, thanks for the info!
