### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by alxjsn** [FortyNorthSecurity/EyeWitness#298]
## OS Used - ALL Information (architecture, linux flavor, etc.)
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
IMAGE_FLAVORS="common docker-based feature-motd systemd"
IMAGE_TOOLS_CHECKOUT="master"
IMAGE_ID="Debian Sid/Unstable"
IMAGE_RELEASE=2017-06-29
IMAGE_CODENAME=debian
IMAGE_DESCRIPTION="Debian Sid/Unstable"
IMAGE_HELP_URL="https://community.scaleway.com"
IMAGE_SOURCE_URL="https://github.com/scaleway/image-debian"
IMAGE_DOC_URL="https://scaleway.com/docs"

## Pastebin link to error you are encountering
https://pastebin.com/cHb0YPTE

## Expected behavior (vs. what you encountered)
Eyewitness should have just skipped the URL instead of causing the entire program to crash.

**Comment by alxjsn** [comment]
Hey @ChrisTruncer,

Yes, an example URL is included in the pastebin report attached in the original comment.

**Comment by ChrisTruncer** [comment]
My apologies, I missed it. 

Thanks for letting me know

**Comment by ChrisTruncer** [comment]
Tested and merged a fix in for this, thanks for letting me know!
