### ISSUE TITLE
inelegant failure

### ISSUE THREAD

**Issue by digininja** [FortyNorthSecurity/EyeWitness#308]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Ubuntu

## Pastebin link to error you are encountering

```
Traceback (most recent call last):
  File "./EyeWitness.py", line 634, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 443, in multi_mode
    url_list, rdp_list, vnc_list = target_creator(cli_parsed)
  File "/home/robin/tools/web/EyeWitness/modules/helpers.py", line 512, in target_creator
    command_line_object.f, command_line_object)
  File "/home/robin/tools/web/EyeWitness/modules/helpers.py", line 427, in textfile_parser
    port_number = int(url_again.split(":")[2].split("/")[0])
ValueError: invalid literal for int() with base 10: '20 2018" version="7.40SVN" xmloutputversion="1.04">'
```

## Expected behavior (vs. what you encountered)
Nice error

## Any additional information
I accidentally used -f rather than -x and passed an xml file in which resulted in the error. It would be nice to catch failure of the split and report on it rather than just crashing.

**Comment by ChrisTruncer** [comment]
This should be relatively easy, I believe "<" should always be the first character. Shouldn't be hard to add in.

**Comment by ChrisTruncer** [comment]
This should now be fixed. Thanks for letting me know!
