### ISSUE TITLE
Issue with VNC and RDP screen shots with Docker for MacOS

### ISSUE THREAD

**Issue by battletux** [FortyNorthSecurity/EyeWitness#320]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Docker CE Version 17.12.0-ce-mac55 (23011) on MacOS Seirra.

## Pastebin link to error you are encountering

```
Starting VNC/RDP Requests (1 Hosts)
EyeWitness.py: cannot connect to X server
```

## Expected behavior (vs. what you encountered)
I expected the Docker instance to take a screen shot of the VNC and RDP login pages. Instead I recived the error message above.

## Any additional information
Tried with the following command: 
```
docker run --rm -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp.X11-unix -v ~/EyeWitness:/tmp/EyeWitness eyewitness -f /tmp/EyeWitness/ips.txt --vnc
```

Won't work for --rdp either, gives the same error message.

**Comment by ChrisTruncer** [comment]
@netanelravid is this something you can check out for the docker image?

**Comment by netanelravid** [comment]
@battletux  Please paste here the output of this command
```bash
echo $DISPLAY
```

**Comment by battletux** [comment]
Hmmm. It just gives me nothing:
```
[5] → echo $DISPLAY


USER @ ~
 [6] →
```

**Comment by netanelravid** [comment]
Try to set it to `:0`, and recheck
```bash
export DISPLAY=':0'
```

**Comment by battletux** [comment]
I've tried that but still no joy:

```
[5] → docker run --rm -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp.X11-unix -v ~/EyeWitness:/tmp/EyeWitness eyewitness -f /tmp/EyeWitness/ips.txt --vnc

################################################################################
#                                  EyeWitness                                  #
################################################################################


Starting VNC/RDP Requests (2 Hosts)
EyeWitness.py: cannot connect to X server :0
```

And:

```
 [6] → echo $DISPLAY
:0

```

**Comment by netanelravid** [comment]
Notice that you execute the command with the volume
```bash
-v /tmp/.X11-unix:/tmp.X11-unix
```

Instead of
```bash
-v /tmp/.X11-unix:/tmp/.X11-unix
```

(You forgot a slash)

**Comment by battletux** [comment]
Yeah typo in the copy paste. Even with the / it still fails:

```
 [8] → docker run --rm -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/EyeWitness:/tmp/EyeWitness eyewitness -f /tmp/EyeWitness/ips.txt --vnc
################################################################################
#                                  EyeWitness                                  #
################################################################################


Starting VNC/RDP Requests (2 Hosts)
EyeWitness.py: cannot connect to X server :0

```

**Comment by netanelravid** [comment]
Try to run
```bash
xhost local:root
```
  And rerun the docker

**Comment by netanelravid** [comment]
@battletux anything new?

**Comment by battletux** [comment]
Appologies, Life got in the way.

The xhost local:root didn't work I got an error to say xhost couldn't be found.

Trying to install xQuartz to see if that helps

**Comment by battletux** [comment]
Ok, that didnt work either:

```
 [5] → xhost local:root
non-network local connections being added to access control list
```
Now to run the image:

```
 [6] → docker run --rm -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/EyeWitness:/tmp/EyeWitness eyewitness -f /tmp/EyeWitness/ips.txt --vnc
################################################################################
#                                  EyeWitness                                  #
################################################################################


Starting VNC/RDP Requests (2 Hosts)
EyeWitness.py: cannot connect to X server /private/tmp/com.apple.launchd.r6Isqddoek/org.macosforge.xquartz:0
```

**Comment by iodbh** [comment]
Same issue in the same environment:
- `MacOS High Sierra 10.13.4 (17E202)`
- `XQuartz 2.7.11`
- `Docker version 17.03.1-ce, build c6d412e` (slightly older)

**Comment by ChrisTruncer** [comment]
@battletux and @netanelravid this good to close, or still need work?

**Comment by iodbh** [comment]
@battletux you need to run something like `xhost +` after changing the Xquartz settings

**Comment by ChrisTruncer** [comment]
@battletux - can you see if the above post from @iodbh helped?

**Comment by ChrisTruncer** [comment]
closing for lack of response

**Comment by incendiary** [comment]
Similar issue for me on linux, solved by:
executing:
`xhost +local:root`

Docker commands:
```
 -it -e DISPLAY=$DISPLAY  \
 -v /tmp/.X11-unix:/tmp/.X11-unix:ro 
```
hope that helps.
