### ISSUE TITLE
Incorrect data in Requests.csv

### ISSUE THREAD

**Issue by kdebacker** [FortyNorthSecurity/EyeWitness#324]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Not relevant

## Pastebin link to error you are encountering
N/A

## Expected behavior (vs. what you encountered)
The "Screenshot Path" column in the "Requests.csv" file is expected to link to the correct screenshot for the specified domain. But the files it specifies often don't exist if the domain contains a page that has been screenshot earlier.

## Any additional information
This is caused by the fact that EyeWitness doesn't save duplicate screenshots for different domains but links the existing screenshot to that domain.

From a quick look at the code it seems like this is not only the case for the Requests.csv file but also for the database (I was not able to verify this since I am not using Python and thus am unable to extract that data from the database).

**Comment by JimmyPom** [comment]
Has anyone taken a look at this yet? 
I'm noticing the same issue. Is there a way to force Eyewitness to save duplicate screens anyway? Or link to the correct, existing, folder?

**Comment by ChrisTruncer** [comment]
This issue should now be fixed, thanks for letting me know!
