### ISSUE TITLE
Problem with start from Docker

### ISSUE THREAD

**Issue by HD421** [FortyNorthSecurity/EyeWitness#332]
Hello, I'm stuck with this error. Maybe you have any advice on it? Thank you.
## Error you are encountering
[*] Error: Please provide a valid folder name/path

## Any additional information
I'm trying to launch EW with this command:
`docker run \
    --rm \
    -it \
    -v ~/EyeWitness:/tmp/EyeWitness \
    eyewitness \
    --single http://www.example.com
    --headless`

**Comment by ChrisTruncer** [comment]
Hi, this is another @netanelravid question. In the meantime, you can always also just download and run EyeWItness locally. However, if you require docker use I will let him answer.

**Comment by HD421** [comment]
Unfortunately(in such case) I'm using Arch and docker is the best solution for me

**Comment by ChrisTruncer** [comment]
Can you use the -d flag to pass the directory to store the results in?

**Comment by netanelravid** [comment]
Try to supply full path to the volume argument instead of ~

**Comment by ChrisTruncer** [comment]
@HD421 - did that help fix the issue?

**Comment by HD421** [comment]
Yes, thank you! Problem solved.
