### ISSUE TITLE
Starting VNC/RDP Requests fails

### ISSUE THREAD

**Issue by angusonmacgyver** [FortyNorthSecurity/EyeWitness#336]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Kali 2018.2 VM

testing on metasploitable. I can connect to VNC on meta with default password "password"

## Pastebin link to error you are encountering
Starting VNC/RDP Requests (2 Hosts)
[*] Error connecting to 192.168.1.115
[*] Error connecting to 192.168.1.115:5900
Traceback (most recent call last):
  File "./EyeWitness.py", line 646, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 574, in multi_mode
    sort_data_and_write(cli_parsed, results)
  File "/root/Desktop/Scanning/DeafultPasswords/EyeWitness/modules/reporting.py", line 219, in sort_data_and_write
    data, cat[0], toc, toc_table, len(pages), cat[1], cat[2], html)
  File "/root/Desktop/Scanning/DeafultPasswords/EyeWitness/modules/reporting.py", line 52, in process_group
    temp = [x for x in group_data if fuzz.token_sort_ratio(
AttributeError: 'module' object has no attribute 'token_sort_ratio"

## Expected behavior (vs. what you encountered)

Eye witness to screenshot VNC and RDP services.

## Any additional information

Happy to provide any more info

**Comment by ChrisTruncer** [comment]
Hi,

I just checked a system with VNC running and it was able to generate a screenshot. I don't know if it is something with the VM you're running, or a specific type of VNC server where it has an issue, but as of now this did capture the image.

**Comment by ChrisTruncer** [comment]
I'll close this for now since I haven't heard back, but if you have any additional information, please feel free to let me know
