### ISSUE TITLE
2nd page of report is not generated

### ISSUE THREAD

**Issue by Viss** [FortyNorthSecurity/EyeWitness#340]
## OS Used - ALL Information (architecture, linux flavor, etc.)
ubuntu 18.04

## Pastebin link to error you are encountering
there is no error message displayed

## Expected behavior (vs. what you encountered)
that all the report pages get generated

## Any additional information
Sadly I have none. I'm not sure why the first page of the report would get generated, but the second wouldnt, and there would be no errors recorded.

**Comment by ChrisTruncer** [comment]
How many urls are you scanning? Is it only a two page report, or is it more than that but somehow missing the second page? Also, any way that you can give the URLs for me to test?

**Comment by ChrisTruncer** [comment]
Closing since this is fixed :)
