### ISSUE TITLE
Still facing the issue

### ISSUE THREAD

**Issue by sakyb7** [FortyNorthSecurity/EyeWitness#357]
I am still facing some issue

Ref: https://github.com/FortyNorthSecurity/EyeWitness/issues/355

Command:
`./EyeWitness.py -f ~/site.com --web`
![screenshot from 2018-09-29 19-18-20](https://user-images.githubusercontent.com/42310984/46246548-4d03f200-c41d-11e8-80ca-32a228e51d63.png)

`./EyeWitness.py -f ~/site.com --headless`

![screenshot from 2018-09-29 19-18-10](https://user-images.githubusercontent.com/42310984/46246550-51300f80-c41d-11e8-9318-d03c79b8dd58.png)

Thank You for the support Sir Cris

**Comment by ChrisTruncer** [comment]
Please do not make duplicate issues
