### ISSUE TITLE
Message: invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by ChrisTruncer** [FortyNorthSecurity/EyeWitness#360]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Ubuntu, but possibly any linux distro

## Pastebin link to error you are encountering
Message: invalid argument: can't kill an exited process

## Expected behavior (vs. what you encountered)
EyeWitness should run

## Any additional information
Calling EyeWitness with sudo

**Comment by ChrisTruncer** [comment]
from Pickles - So the geckodriver log mentioned firefox not being able to be run as root when it's owned by another user.  So running without root gives perm issues when trying to mkdir.  So if you chmod 777 everything in the directory it seems to be working.

**Comment by ChrisTruncer** [comment]
Documented this in case anyone else has this issue

**Comment by dropocol** [comment]
@ChrisTruncer I am facing the same issue where firefox can't be run as root in another user session. 
I can run EyeWitness if I change to root using 'sudo su' then it works perfectly but I don't wanna do that every time.

I read your solution above but can't figure out which directory to chmod. Any help would be appreciated. Thanks

**Comment by ChrisTruncer** [comment]
A quote from Pickles who found the fix - "Not sure if both need to changed, but I did a chmod on the Eyewitness folder, and specifically the geckodriver.log inside."

**Comment by MenToS128** [comment]
The banal change of the rights to 777 on geckodriver.log helped me. 
Fast solution sudo chmod 777 geckodriver.log
Good luck and thanks for this tool. :)
