### ISSUE TITLE
Unable to download source while using IP address instead of hostname

### ISSUE THREAD

**Issue by pupattan** [FortyNorthSecurity/EyeWitness#361]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Linux

## Expected behavior (vs. what you encountered)
Its unable to download proper source content while using IP address instead of hostname (python.org)
Command -
` python /home/ss/EyeWitness/Eyeingle 23.253.135.79:80 --headless --no-prompt -d /home/ss/EyeWitness/reports/795`
It produces "/home/ss/EyeWitness/reports/795/source/http.23.253.135.79.txt" with the following content
```
<html><head></head><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
```

## Any additional information
But while using hostname it works perfectly fine

**Comment by ericnyamu1** [comment]
maybe the remote end is blocking direct ip access to the website.

**Comment by ericnyamu1** [comment]
> 
> ## OS Used - ALL Information (architecture, linux flavor, etc.)
> 
> Linux
> ## Pastebin link to error you are encountering
> ## Expected behavior (vs. what you encountered)
> 
> Its unable to download proper source content while using IP address instead of hostname (python.org)
> Command -
> ` python /home/ss/EyeWitness/Eyeingle 23.253.135.79:80 --headless --no-prompt -d /home/ss/EyeWitness/reports/795`
> It produces "/home/ss/EyeWitness/reports/795/source/http.23.253.135.79.txt" with the following content
> 
> ```
> <html><head></head><body><h1>503 Service Unavailable</h1>
> No server is available to handle this request.
> ```
> 
> ## Any additional information
> 
> But while using hostname it works perfectly fine

maybe the remote end is blocking direct ip access to the website.

**Comment by pupattan** [comment]
Thanks for the update.
