### ISSUE TITLE
Can't Kill an exited process

### ISSUE THREAD

**Issue by jdonsec** [FortyNorthSecurity/EyeWitness#362]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Ubuntu 18.0

## Pastebin link to error you are encountering
https://pastebin.com/u88S8Bef

## Expected behavior (vs. what you encountered)
Expected the tool scan produce screenshots domains.txt

**Comment by ChrisTruncer** [comment]
Please review #360 and post any messages in there to prevent duplicates

Thanks!

**Comment by jdonsec** [comment]
Thank you! #360 solution worked.
