### ISSUE TITLE
Save complete results to database [feature idea]

### ISSUE THREAD

**Issue by Keldorb** [FortyNorthSecurity/EyeWitness#366]
Hey there!
Great work on the tool so far. It makes my work a whole lot easier. 
I sometimes scan a huge number of IPs over multiple subnets. Sometimes i edit the results to show only relevant data in a report or something like that. That for it would be nice if you have a Database or some technique like that to querry the results. In terms of a database i would love to querry some specific host to get all findings of it. Another example is to be able to querry alle results which are "Splash Pages" for example. Is there a way to do this allready and i dont know of it? If there is a way to do this a tutorial would be really nice. 

Thanks and keep up the good work.

**Comment by ChrisTruncer** [comment]
Hi,

There is a database that's generated with every EyeWitness run. It's the ew.db file contained within the output folder. You could always use a sqlite browser or any other way to open it and interact with the db. There are other files that interact with it, such as the Search.py file. It lets you search the the database for a specific system(s) you are interested in and will generate a new report based on what it finds.

Hope that this helps
