### ISSUE TITLE
Message: connection refused

### ISSUE THREAD

**Issue by jayjani007** [FortyNorthSecurity/EyeWitness#367]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Linux

## Any additional information
I am getting **Message: connection refused** error while applying `python EyeWitness.py -f urls.txt --web` command to the terminal of Kali Linux

![untitled](https://user-images.githubusercontent.com/20972659/48469956-1b50ba00-e816-11e8-964d-af8163d99377.png)

**Comment by ChrisTruncer** [comment]
You might need to update EyeWitness. I just tested installing EyeWitness on a clean Kali vm and it was able to install without any issues

**Comment by ChrisTruncer** [comment]
Re-run the setup script, it will make sure you have the latest version of geckodriver, and that should solve the problem
