### ISSUE TITLE
Firefox now required

### ISSUE THREAD

**Issue by Raikia** [FortyNorthSecurity/EyeWitness#370]
Due to #369, Firefox is now required.  You should add it to the setup script since running this on DigitalOcean Ubuntu servers gives "Message: Unable to find a matching set of capabilities" without installing firefox

**Comment by ChrisTruncer** [comment]
I'll be happy to look into this and do it immediately for you @Raikia !

By the way, didn't you mention you were going to have some code for me about 3 years ago?

**Comment by ChrisTruncer** [comment]
Fixed now, thanks for opening it buddy!
