### ISSUE TITLE
[Docker] non-existent package firefox-esr breaks installation

### ISSUE THREAD

**Issue by Alphakilo** [FortyNorthSecurity/EyeWitness#372]
The current Docker instructions result in an unusable Docker Image:

```
alphakilo@hostname_redacted:~/src/eyewitness_upstream master 3m40s ± docker run --rm -it -v ~/EyeWitness:/tmp/EyeWitness eyewitness_upstream --single http://www.google.com --headless
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown.

```

Full build log is here:
https://gist.github.com/Alphakilo/78ed490c079dd9b6f399cde890ab1f0f

Is ESR required or can we run on rapid release?

**Comment by HD421** [comment]
I can confirm this problem. Bump thread.

**Comment by ChrisTruncer** [comment]
You can try rapid release and let me know. I personally don't maintain the docker image, I believe that is @netanelravid. Any fixes or pull requests with the fixes are definitely accepted :)

**Comment by Alphakilo** [comment]
@ChrisTruncer This should also affect all Ubuntu installations as well.
I can't notice any adverse behaviors with rapid release so far, the `--web` flag does what it should.
Although the screenshot does only contain the first screen, but I believe that is expected behavior?

@HD421 Could you confirm that #375 works for you?

**Comment by netanelravid** [comment]
Why do we need the firefox-esr?
Can we run without it?

**Comment by ChrisTruncer** [comment]
@netanelravid - I removed the --headless option because it relied on phantomjs which has been deprecated from selenium. The --web option uses Firefox, but headlessly within EyeWitness. Therefore, the dependency is now to have firefox installed which is why I have been using firefox-esr. But it looks like it **might** not be a package in Ubuntu, which I will have to investigate later in the evening

**Comment by ChrisTruncer** [comment]
I've pushed an update for Ubuntu Distros to use "firefox" and not "firefox-esr". This should be good to go on the Ubuntu side. Not sure, but possible the Docker image might need updated?

**Comment by netanelravid** [comment]
The dockerfile is depended on the setup file, so its supposed to be good enough.

**Comment by HD421** [comment]
@ChrisTruncer Seems to be fixed. Just now I successfully build frew eyewitness docker container, thank you!

**Comment by ChrisTruncer** [comment]
OK, closing this out, tahnks
