### ISSUE TITLE
error with rm at end of setup

### ISSUE THREAD

**Issue by digininja** [FortyNorthSecurity/EyeWitness#373]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali

## Pastebin link to error you are encountering

I've just done a fresh install of the latest Github code on a new Kali box. I spotted this error from `rm` at the end of the setup process.

```
2018-11-29 13:02:17 (380 KB/s) - ‘geckodriver-v0.22.0-linux64.tar.gz’ saved [3866448/3866448]

geckodriver
rm: cannot remove '/usr/bin/geckodriver': No such file or directory
[*] Setup script completed successfully, enjoy EyeWitness! :)
```
Might be nothing important but should be tidied up.

If I get chance I'll try to work out why but got to test first.

## Expected behaviour (vs. what you encountered)

Shouldn't see an error.

## Any additional information

A baby jellyfish is called an ephyra.

**Comment by ChrisTruncer** [comment]
Yeah, I should check for that.

I never knew about ephyras!

**Comment by ChrisTruncer** [comment]
Just pushed a fix for this, thanks for the heads up!
