### ISSUE TITLE
WebDriverException error

### ISSUE THREAD

**Issue by 0xhexmex** [FortyNorthSecurity/EyeWitness#374]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Kali

## Pastebin link to error you are encountering

https://pastebin.com/eJe6Hqie

## Expected behavior (vs. what you encountered)

No error, or "[*] Hit timeout limit when connecting to...." message

## Any additional information

Command line used was:

`./EyeWitness.py --web -x nessus_scan.nessus -d outputdir --no-prompt`

I'm running a very large scan (over 7000 services) and this error seems to happen randomly. I'm through about 430 services at the moment, and 9 of them have produced that same error message

**Comment by ChrisTruncer** [comment]
If you can share the Nessus or the file containing urls I can look at it, otherwise it’s going to be hard for me to troubleshoot.

**Comment by 0xhexmex** [comment]
Really appreciate the quick response! Unfortunately that's a no-go since this is an internal test I'm doing :/. If I ever run into this on an external test I'll reply back to this thread. Thanks for your work. Awesome tool

**Comment by ChrisTruncer** [comment]
Sorry, wish I could have given better help. As I'm sure you can imagine, it's just hard to test an issue I can't recreate. Hope all gets working for you

**Comment by 0xhexmex** [comment]
Totally understand no worries man :). I had better luck after upgrading the geckodriver (https://github.com/mozilla/geckodriver/releases) from v0.22 to v0.23, so that may help others that run into this issue just FYI.

**Comment by routeback** [comment]
Experienced a similar issue. I've scripted a fix to automate this geckodriver update process in Kali:

https://raw.githubusercontent.com/routeback/bashscripts/master/remote_testing_appliance/geckodriver_update.sh

**Comment by ChrisTruncer** [comment]
I’ll do some testing on my end, and then I’ll try to push out an update to the setup process to use a later version of gecko driver


________________________________

**Comment by routeback** [comment]
The only modification I would recommend adding to my script if you do proceed with merging it would be to check for the machine type as your setup.sh script already does, e.g.:
```
MACHINE_TYPE=`uname -m`
if [ ${MACHINE_TYPE} == 'x86_64' ]; then
        url=$(echo "$json" | jq -r '.assets[].browser_download_url | select(contains("linux64"))')
        else
        url=$(echo "$json" | jq -r '.assets[].browser_download_url | select(contains("linux32"))')
fi
```

**Comment by ChrisTruncer** [comment]
I just pushed to the repo an update to the setup script. It now pulls down version 0.24.

Hope this helps!


________________________________
