### ISSUE TITLE
Message Timeouts using --web argument 

### ISSUE THREAD

**Issue by PjMpire** [FortyNorthSecurity/EyeWitness#377]
## OS Used - ALL Information (architecture, linux flavor, etc.)

PRETTY_NAME="Parrot GNU/Linux 4.4"
NAME="Parrot GNU/Linux"
ID=parrot
ID_LIKE=debian
VERSION="4.4"

##  error you are encountering

--web option giving Message:Timout. --headless option worked prior to depreceation

## Expected behavior (vs. what you encountered)
Successful screenshot

## Any additional information
Downloaded and ran setup.sh installing all dependencies including firefox.

--headless option used to work flawlessly on previous version until error occured regarding version of selenium and phantomjs. Now --headless option has been removed I am unabel to get successful results using the --web option.

Internet connectivity confirmed ok

**Comment by ChrisTruncer** [comment]
I don't support Parrot, that's only been by others submitting the options to me and allowing it in. Headless was removed because phantomjs is no longer supported. You **could** try installing just "firefox" instead of "firefox-esr" and let me know if that works

**Comment by ChrisTruncer** [comment]
closing with no response. If you find a fix, please submit a pull request.
