### ISSUE TITLE
suggesstion

### ISSUE THREAD

**Issue by xxnbyy** [FortyNorthSecurity/EyeWitness#378]
I hope you can support the masscan xml result ,when the ip is too much ,masscan is a better choice.

**Comment by ChrisTruncer** [comment]
This already supports masscan xml

**Comment by xxnbyy** [comment]
> 
> This already supports masscan xml
> […](#)
> On Dec 11, 2018, at 1:56 AM, xxnbyy ***@***.***> wrote: I hope you can support the masscan xml result ,when the ip is too much ,masscan is a better choice. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Oh,i got it,thx
