### ISSUE TITLE
Message: timeouts (sic) - Eyewitness on CentOS

### ISSUE THREAD

**Issue by rgritzo** [FortyNorthSecurity/EyeWitness#380]
## OS Used - ALL Information (architecture, linux flavor, etc.)
CentOS Linux release 7.6.1810 (Core), x86_64

## Pastebin link to error you are encountering
(short enough I can paste it here....)
[user@test]$ /opt/EyeWitness-master/EyeWitness.py --web --single https://www.google.com -d output 
################################################################################
#                                  EyeWitness                                  #
################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################
Attempting to screenshot https://www.google.com
Message: timeouts
[user@test]$

(behavior is the same regardless of --single or -f <filename>)

## Expected behavior (vs. what you encountered)
verified that EyeWitness is not accessing the website, the timeouts seem to be coming from the internal connection to the gecko / firefox / selenium driver.

## Any additional information
Latest EyeWitness code, 
setup.sh modified to work with CentOS (will post the changes once we get this working), setup.sh completes successfully.
reviewed the geckodriver log, and fixed the errors there (had to install dbus-x11 package), so no errors in the geckodriver log.
timeouts seem to occur at or about here:
   driver = create_driver(cli_parsed, user_agent)
    ... within the worker_thread....

selinux is running, but does not matter if it is enforcing or permissive.

This used to work, but at some point in the last 6 to 9 months it broke.
I see the firefox --headless processes, the Xvfb process etc starting....
I am at the limit of my troubleshooting ability here, so any help is appreciated!

thanks....
r.

**Comment by rgritzo** [comment]
I did those steps listed (206 to 216) and installed the geckodriver, but the error still is occurring.   

here is the geckodriver log:
1548127026547	geckodriver	INFO	Listening on 127.0.0.1:43668
1548127026594	mozprofile::profile	INFO	Using profile path /tmp/rust_mozprofile.yqnrm1jULr9u
1548127026596	geckodriver::marionette	INFO	Starting browser /usr/bin/firefox with args ["--headless"]
1548127026609	geckodriver::marionette	INFO	Connecting to Marionette on localhost:43636
*** You are running in headless mode.
1548127026830	addons.xpi	WARN	disabling legacy extension test@autoew.net
1548127026830	addons.xpi	WARN	disabling legacy extension test@autoew.net
1548127026832	addons.xpi	WARN	disabling legacy extension test@autoew.net
1548127027744	Marionette	INFO	Listening on port 43636

and I see the following processes still sitting there running, even after the timeout message:
user      8496  0.0  1.5 106156 15508 pts/0    S    03:17   0:00 Xvfb -br -nolisten tcp -screen 0 1920x1080x24 :1009
user      8502  0.7 15.6 2120364 155448 pts/0  Sl   03:17   0:02 /usr/bin/firefox --headless --marionette --profile /tmp/rust_mozprofile.yqnrm1jULr9u
user      8554  0.0  5.3 1639584 52984 pts/0   Sl   03:17   0:00 /usr/lib64/firefox/firefox -contentproc -childID 1 -isForBrowser -intPrefs 42:30|44:30| -boolPrefs 5:1|61:1
user      8626  0.0  0.0  58892   884 pts/0    S    03:17   0:00 dbus-launch --autolaunch=a297c757fe24408288a2a573a3edc4a2 --binary-syntax --close-stderr
user      8627  0.0  0.1  66184  1496 ?        Ssl  03:17   0:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
user      8661  0.0  3.9 1625176 39616 pts/0   Sl   03:17   0:00 /usr/lib64/firefox/firefox -contentproc -childID 2 -isForBrowser -intPrefs 42:30|44:30| -boolPrefs 5:1|61:1

netstat shows the listening services started sitting in TIME_WAIT until they time out.

and - i see the profile path in /tmp being created.  i rooted around in there but did not see any obvious failings or issues...

i have done so much to this VM troubleshooting this that for the moment I need to revert back to it's initial state and do some workaround on this.   in the meantime i am going to build a new pristine CentOS 7 vm and pick this troubleshooting up again as i have time.

any other insights appreciated!  

thanks!

**Comment by ChrisTruncer** [comment]
I think at this point you might have to test on a new VM. You could also try installing a later version of GeckoDriver on your system in case that is what is causing this issue.

**Comment by rgritzo** [comment]
building up the VM now, will work through it and post results here..

**Comment by ChrisTruncer** [comment]
I'm going to close this out since it seems like this has gone dead. If you do end up getting everything set up, please feel free to post results here.
