### ISSUE TITLE
RDP Library not found

### ISSUE THREAD

**Issue by kirtiso** [FortyNorthSecurity/EyeWitness#387]
Hello,

I'am using kali linux and try to install eyewitness but it give error.
[*] RDP libraries not found.
[*] Please run the script in the setup directory!

I already install pip install rdpy and rdp but again and again same error.Please help me to resolve it.

**Comment by digininja** [comment]
Did you run the setup script?

**Comment by kirtiso** [comment]
NO,i did not run and.And if it is run then how??

**Comment by digininja** [comment]
If you've downloaded it from GitHub then as the message says, run the
script in the setup directory.

**Comment by kirtiso** [comment]
NO any message show but when i'am using ./EyeWitness.py then an error message show
 [] RDP libraries not found.
[] Please run the script in the setup directory!

**Comment by kirtiso** [comment]
Yes , I run the script setup but now i got different error 
~/EyeWitness# ./EyeWitness.py

################################################################################
#                                  EyeWitness                                  #
################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################

[*] Error: You didn't specify a file! I need a file containing URLs!
usage: EyeWitness.py [--web] [--rdp] [--vnc] [--all-protocols] [-f Filename]

**Comment by digininja** [comment]
And did you specify a file containing URLs as this error message states?

**Comment by kirtiso** [comment]
When i'am specify url it shows error

root@kali-test-workstation:~/EyeWitness# ./EyeWitness.py --web https://google.com

################################################################################
#                                  EyeWitness                                  #
################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################

usage: EyeWitness.py [--web] [--rdp] [--vnc] [--all-protocols] [-f Filename]
                     [-x Filename.xml] [--single Single URL] [--no-dns]
                     [--timeout Timeout] [--jitter # of Seconds]
                     [--threads # of Threads]
                     [--max-retries Max retries on a timeout]
                     [-d Directory Name] [--results Hosts Per Page]
                     [--no-prompt] [--user-agent User Agent]
                     [--cycle User Agent Type]
                     [--difference Difference Threshold]
                     [--proxy-ip 127.0.0.1] [--proxy-port 8080]
                     [--proxy-type socks5] [--show-selenium] [--resolve]
                     [--add-http-ports ADD_HTTP_PORTS]
                     [--add-https-ports ADD_HTTPS_PORTS]
                     [--only-ports ONLY_PORTS] [--prepend-https]
                     [--active-scan] [--resume ew.db] [--ocr]
EyeWitness.py: error: unrecognized arguments: https://google.com
root@kali-test-workstation:~/EyeWitness#

**Comment by ChrisTruncer** [comment]
Please follow the readme or look at any of the blog posts which clearly state how to use the tool. This will help you get started with it.

**Comment by CyberGhost03** [comment]
Tried everything on here with no luck still the same [] RDP libraries not found.
[] Please run the script in the setup directory! I'm on Ubuntu 16.04.6
