### ISSUE TITLE
Ineffective parsing of WebDriver errors

### ISSUE THREAD

**Issue by aph3rson** [FortyNorthSecurity/EyeWitness#390]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Linux, 2019.1, x64 (on ESXi)

## Pastebin link to error you are encountering
I'm unable to grab a pastebin due my scanning environment being in a secured area. However, I can say that generic `[*] WebDriverError when connecting to https://[host]:[port]/` errors frequently appear in the scan. Before each instance of this in `selenium_module.py` and `phantomjs_module.py`, I changed the exception to be printed to the console. From the message that was printed, selenium was redirecting to `about:neterror` pages for the following types of error:

* TCP reset
* Network timeout 
* SSL handshake failure
* Connection failure
* Redirect loop

## Expected behavior (vs. what you encountered)
I would hope that EyeWitness could either correctly categorize these errors, or include their status in the report. Optionally, for potentially-ephemeral errors (e.g. timeouts, network-layer issues), it would try again following the `--max-retries` argument.

**Comment by ChrisTruncer** [comment]
If you can provide URLs to validate this against, I am happy to look into it. I'm not exactly certain at what point it gets to be overkill to have a separate error and categorization for every single error that a browser might encounter. That's the reason that EyeWitness is set up as it is currently. TO have separate pages for every single of the above errors might be a bit much, and at the moment a generic error message I think is sufficient.

With that said, I'm also open to reviewing a pull request if you already have modified the code base (which it sounds like you might have) to separate these errors.

**Comment by ChrisTruncer** [comment]
Closing since I haven't received a response, at this point I plan on leaving the errors as is because I don't think there's a significant amount of value to add the additional information. However, I am always happy to review a pull request in the event someone ones to break them out.
