### ISSUE TITLE
Adding CPE identifiers to each discovered technology [feature idea]

### ISSUE THREAD

**Issue by HuntedCodes** [FortyNorthSecurity/EyeWitness#392]
EyeWitness does a nice job of automatically importing nmap results, and displaying relevant metadata alongside screenshots of web services in the report. It would be handy for automation and integration if metadata for discovered technologies also included [CPE identifiers](https://nvd.nist.gov/products/cpe), for example:

- Software: `Apache/2.2.14`
- CPE ID: `cpe:2.3:a:apache:http_server:2.2.14:*:*:*:*:*:*:*`

This could be leveraged by users to [automatically map results to CVE's](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&cves=on&cpe_version=cpe%3a%2fa%3aapache%3ahttp_server%3a2.2.14), or even include the CVE count or CVE's directly in the EyeWitness report.

Nmap's version detection will do this for operating systems. Application level CPE's are [officially supported](https://nmap.org/book/man-version-detection.html), but I haven't really seen them in practice.

```
...
Service Info: OS: Windows; CPE: cpe:/o:microsoft:windows
...
```

Is there any interest in such a feature?

**Comment by ChrisTruncer** [comment]
I am absolutely open to having something like that added in. At the moment, I don’t know if that’s something I could personally undertake, but I do see the value in having that information available. The biggest thing will be to find the source where it will receive that information, and maintaining a database of future mappings.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by HuntedCodes** [comment]
After doing a bit more digging, nmap has a lot of application CPE identifiers in their [fingerprint database](https://raw.githubusercontent.com/nmap/nmap/master/nmap-service-probes) (search for `cpe:/a`), but many records don't. Point is that eventually EyeWitness could take advantage of those, when they become more complete. This is the cleaner solution, but requires people amending the nmap fingerprint database.

There is a third party NSE script, [nmap-vulners](https://github.com/vulnersCom/nmap-vulners), that  pulls down CPE identifiers for discovered services from the Vulners API, storing them in the nmap XML files. EyeWitness could let the NSE script do the matching, and just parse resulting XML for identifiers. The upside is that it's less work and code to maintain. The downside is that it relies on users having the NSE script installed.

**Comment by ChrisTruncer** [comment]
I'm definitely open to getting something like this added in. I'm going to close the issue since there's not a code problem, but I'm not going to lock this to continue discussion on the topic. The only thing is I don't think most people will have that external NSE script installed, so it's hard to write code looking for that information when it's not given by default. If there is any other easy mapping, then it'd be interesting to see the integration that could be built.
