### ISSUE TITLE
Creation of the docker image permanently stores proxy information

### ISSUE THREAD

**Issue by Noir-** [FortyNorthSecurity/EyeWitness#394]
## OS Used - ALL Information (architecture, linux flavor, etc.)

    $ uname -a
    Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux
    $ docker --version
    Docker version 18.09.5, build e8ff056

## Pastebin link to error you are encountering

Not applicable. 

## Expected behavior (vs. what you encountered)

I'm behind a proxy server for internet access. In order to download and build images I configured the docker environment accordingly to this post:

https://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy

I skipped the `NO_PROXY` part because I haven't planned to access the inTRAnet in the building process.

After I built the docker image as described in the documentation, I deleted the proxy environment variables from the Docker configuration file and restarted the Docker daemon.

When I tried screenshotting a site in the inTRAnet, the request always ran into a timeout. In the proxy logs I noticed that the container still tries to use the proxy. So it seems that in the building process, the environment variables where hardcoded into the container. Changing the variables in the docker environment or adding the `NO_PROXY` section didn't had any effect.

This shouldn't happen since the environment can change any time in the future.

Besides that, I also noticed some other URLs accessed by the container which are not relevant for creating a screenshot:

```
location.services.mozilla.com:443
snippets.cdn.mozilla.net:443
shavar.services.mozilla.com:443
tracking-protection.cdn.mozilla.net:443
```

**Comment by Noir-** [comment]
Never mind. I overlooked a local configuration. But the unwanted URL part is still an issue.

**Comment by ChrisTruncer** [comment]
The URLs are something that I would not be able to modify. EyeWitness uses Mozilla Firefox to go to the different websites, capture screenshots, etc. Firefox itself is what is making those requests, not EyeWitness, as part of how the browser operates.
