### ISSUE TITLE
Xvfb Error in New load

### ISSUE THREAD

**Issue by Shad0wRec0n** [FortyNorthSecurity/EyeWitness#397]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Kali Linux 2019.2 
Python 2.7

 Chris, Thanks for a great product.  In running this on a new machine load I am getting the Xvfb and a few other dependencies that are not able to load and my hunt to find them came to no avail. I tried some loads of xvfb, xvfbwrapper, etc but none are located.  I dont necessarily need to be headless at the moment so if that can be dropped then that is fine. 

This is the output after running the setup script (I am in python 2.7 if that causes any issues) 

#                          EyeWitness Setup                           #
#######################################################################

Reading package lists... Done
[*] Installing Kali2 Dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package xvfb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package cmake is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'cmake' has no installation candidate
E: Unable to locate package qt4-qmake
E: Package 'xvfb' has no installation candidate
E: Unable to locate package tesseract-ocr
[*] Upgrading paramiko
Requirement already up-to-date: paramiko in /usr/lib/python2.7/dist-packages (2.4.2)

##_______________________________________

 If I try to go through and run a test on a few IPs I get this 

################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################

Traceback (most recent call last):
  File "./EyeWitness.py", line 612, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 432, in multi_mode
    display = Display(visible=0, size=(1920, 1080))
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 53, in display_class
    cls.check_installed()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/xvfb.py", line 40, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python2.7/dist-packages/easyprocess/__init__.py", line 182, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error!

**Comment by ChrisTruncer** [comment]
Hi, is there any way to try using a different mirror on your VM? It looks like the install is failing by not installing some dependencies (such as xvfb). When I try to install the xvfb package on my system, it is there and I am able to install it. I also just tested on a new Kali install and it installed successfully and did capture screenshots and generate a report. I think if you try different mirrors it should work, but it’s worth testing.

**Comment by Shad0wRec0n** [comment]
Chris - thanks for the quick response. I will spin a few up and do some trials.

**Comment by Shad0wRec0n** [comment]
followed up with a new download and boot image and it went through just fine.  Thanks for your help.
