### ISSUE TITLE
Centos installation broken

### ISSUE THREAD

**Issue by DannyCork** [FortyNorthSecurity/EyeWitness#399]
## OS Used
CentOS Linux release 7.6.1810 (Core) 

## Error
```
#######################################################################
#                          EyeWitness Setup                           #
#######################################################################

[Error]: \S is not supported by this setup script.
```

## Expected behavior (vs. what you encountered)
setup should correctly detect the os.

## Any additional information
Issue is with line 4 of setup.py
osinfo=`cat /etc/issue|cut -d" " -f1|head -n1`

This is incorrect for Centos. A better determiner would be 
```
$more /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

```

**Comment by ChrisTruncer** [comment]
merged
