### ISSUE TITLE
All of the --cycle options are failing.

### ISSUE THREAD

**Issue by jonathan-plisken** [FortyNorthSecurity/EyeWitness#410]
## OS Used - ALL Information (architecture, linux flavor, etc.)

4.19.0-kali5-amd64

## Pastebin link to error you are encountering

[*] Starting requests for User Agent wget1.9.1 (107 Hosts)
Message: Failed to set preferences: Unable to read profile preferences file

Message: Failed to set preferences: Unable to read profile preferences file

Message: Failed to set preferences: Unable to read profile preferences file

Message: Failed to set preferences: Unable to read profile preferences file

Message: Failed to set preferences: Unable to read profile preferences file

Message: Failed to set preferences: Unable to read profile preferences file

Message: Failed to set preferences: Unable to read profile preferences file

[*] Starting requests for User Agent Googlebot2.1 (107 Hosts)
Message: Failed to set preferences: Unable to read profile preferences file
...

## Expected behavior (vs. what you encountered)

I expected eyewitness to cycle through all of these different browser types / user agents, and report the differences.

## Any additional information

The software works fine without --cycle, but attempting to use that flag causes it to rotate through the different user agents and fail at each one of them, in turn.

**Comment by ChrisTruncer** [comment]
This should now be fixed in the latest version, thanks!
