### ISSUE TITLE
Error in EyeWitness.py & helpers.py + fail to access Requests.csv

### ISSUE THREAD

**Issue by Plexias** [FortyNorthSecurity/EyeWitness#412]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Virtualization: vmware
Operating System: Parrot GNU/Linux 4.7
Kernel: Linux 5.2.0-2parrot1-amd64
Architecture: x86-64

## Pastebin link to error you are encountering
https://pastebin.com/6pdEz4hE

## Any additional information
setup.sh pastebin https://pastebin.com/aeX8E7ZA

**Comment by SocialAnxty** [comment]
I have this same issue, is there any update on a fix?

**Comment by ChrisTruncer** [comment]
I'm closing this for the time being since this should not be present on the EyeWitness 3 version just released. If it still is, please feel free to re-create the issue (but make sure you are using the latest version of EyeWitness and have run the setup script)
