### ISSUE TITLE
Hit timeout limit when connecting to

### ISSUE THREAD

**Issue by asmirkonjevic1** [FortyNorthSecurity/EyeWitness#413]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Linux - updated to last version

## Expected behavior (vs. what you encountered)
Hi, when I try to run eyewitness against 3 hosts with http and https so 6 urls total I'm only able to get screenshot from 1 host, for other's I get "Hit timeout limit when connecting to ... " error.
Hosts used:
youtube.com
google.com
github.com

Starting Web Requests (6 Hosts)
Attempting to screenshot http://google.com
Attempting to screenshot https://google.com
Attempting to screenshot http://youtube.com
[*] Hit timeout limit when connecting to https://google.com, retrying
[*] Hit timeout limit when connecting to https://google.com
Attempting to screenshot https://youtube.com
[*] Hit timeout limit when connecting to http://youtube.com, retrying
[*] Hit timeout limit when connecting to https://youtube.com, retrying
[*] Hit timeout limit when connecting to http://youtube.com
Attempting to screenshot http://github.com
[*] Hit timeout limit when connecting to https://youtube.com
Attempting to screenshot https://github.com
[*] Hit timeout limit when connecting to https://github.com, retrying
[*] Hit timeout limit when connecting to http://github.com, retrying
[*] Hit timeout limit when connecting to https://github.com
[*] Hit timeout limit when connecting to http://github.com
Finished in 86.1266410351 seconds

Command Used: ./EyeWitness.py -f urls.txt --web --threads 5 --prepend-https

I tried playing with threads and timeout but same result.
It doesn't matter which domains I use I'm still having same issue. 

Anyone had similar issues?

Thanks

**Comment by Mouhannad963** [comment]
same problem !!

**Comment by Usama-Hanif131** [comment]
Default timeout is set to 7 , i just fixed the issue by setting the timeout to 120

command: eyewitness --web -x <nmap-output.xml> -d <output-directory> --timeout 120
