### ISSUE TITLE
ERROR: You didn't give me a valid file name! I need vaild file containing URLs!

### ISSUE THREAD

**Issue by kd54726** [FortyNorthSecurity/EyeWitness#419]
I created a **all.txt** file in which included urls : https://www.google.com , https://facebook.com
 
I ran the code like : **eyewitness -f all.txt --web**

But It say : 
**ERROR: You didn't give me a valid file name! I need vaild file containing URLs!**

I have tried various methods but it doesn't work. please help me out

**Comment by ChrisTruncer** [comment]
you didn't provide any of the information requested when creating a ticket.

I would also call EyeWitness as ./EyeWitness.py assuming you cloned this down.

Please also provide the full path the the text file?

Can you elaborate on what you tested?

**Comment by kd54726** [comment]
@ChrisTruncer 
In my machine I don't have to type "./eyewitness" , I can type " eyewitness" from any dir it works.

I have created a all.txt file in the location : **~/Documents/test/all.txt** with the above mention urls

I wanted to test eyewitness first with simple url but it is not working

**Comment by ChrisTruncer** [comment]
I'm sorry, but without all of the information that's requested, I don't have a way to troubleshoot this based on what you've provided. Please feel free to open another issue and provide everything I need to know to help

**Comment by kd54726** [comment]
Can you tell me what kind of more information do you need?
I need to get eyewitness working urgently

<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=eadf9103-3ec4-4ed2-a9f2-02984b1f8324>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=eadf9103-3ec4-4ed2-a9f2-02984b1f8324>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
