### ISSUE TITLE
pip error in setup.sh

### ISSUE THREAD

**Issue by WhiteFerrari** [FortyNorthSecurity/EyeWitness#420]
The setup script is calling pip, which is being mapped to pip3 in linux now. 

If python2 is still being used, explicitly use pip2 to install the python2 packages. 

Else, consider porting to python3 (i'm sure you are already aware of this). 

As a last resort, add documentation that requires the end user to do this themselves, as this will likely save them debugging time. 

Cheers!

**Comment by ChrisTruncer** [comment]
I didn't realize that it was being mapped to pip3, I don't know if that's being enforced across all distros.

I am going to close this, not because it's not valid, but because I do have a fix for this already. EyeWitness has been ported to a Python3 version. Right now it's just in a Beta state trying to see if anyone can find any bugs in it (https://github.com/FortyNorthSecurity/EyeWitness/tree/Python3). I'll give it a little bit longer to let anyone try it out and find bugs, otherwise it will be merged in shortly.

**Comment by digininja** [comment]
In Ubuntu 18.04 and Kali latest, pip is still mapped to 2.7.

**Comment by WhiteFerrari** [comment]
Interesting, I'm on Ubuntu 19.04 and the latest Kali, and seeing otherwise -- but perhaps i made a configuration change a while ago and have forgotten. 

Was just looking to share in case others ere experiencing the same issue. 

Cheers!

**Comment by WhiteFerrari** [comment]
@digininja Just to confirm, as my peers are seeing the same. Im running Ubuntu 19.04 and the latest version of Kali. Both yielded the same results. 

```
➜ EyeWitness git:(master) pip -V              
pip 19.2.3 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
```

**Comment by ChrisTruncer** [comment]
I'd love if you or your peers would like to try the Python3 version and submit any bugs as you encounter them. @digininja has been helping with this a ton, and anyone else looking at it will help ensure coverage so it works well once I merge it in.

**Comment by digininja** [comment]
A Kali which I just did a full update on is giving me this:

```
$ pip -V
pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)

$ cat /etc/lsb-release 
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
```

And Ubuntu:

```
$ pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```

**Comment by WhiteFerrari** [comment]
@digininja super interesting...i wont pay too much mid to it. 

@ChrisTruncer Happy to try the python3 version. Where can i pull it from?

**Comment by digininja** [comment]
For the Python 3 version, check out the Python 3 branch. You'll need to
re-run the setup script as it brings in different things.
