### ISSUE TITLE
Eyewitness not recognizing --headless

### ISSUE THREAD

**Issue by j0eii** [FortyNorthSecurity/EyeWitness#421]
ftw: https://github.com/xme/dockers/issues/15

I just did a new build of the Dockerfile and it looks like the version of Eyewiteness that is installed no longer recognizes the --headless parameter as called in entrypoint.sh. I get this output:

EyeWitness.py: error: unrecognized arguments: --headless

Sadly I rebuilt on top of the old image that was working, no now I am broken :-(

## resolve

Resolved this myself by grabbing an older version of EyeWitness, so in the Dockerfile I now have:
```
# RUN git clone https://github.com/ChrisTruncer/EyeWitness.git
RUN wget https://github.com/FortyNorthSecurity/EyeWitness/archive/2.2.2.tar.gz && tar -xzf 2.2.2.tar.gz && mv EyeWitness-2.2.2 EyeWitness
```

please change the dockerfile content to fix this issue..

I have experienced the same issue and the above is a very good quick fix.

thanks.

**Comment by ChrisTruncer** [comment]
I'm going to close this since this is on the old version of EyeWitness. However @netanelravid might want to review this to make sure the docker image setup is updated accordingly.
