### ISSUE TITLE
Error when running and not getting any results.

### ISSUE THREAD

**Issue by SocialAnxty** [FortyNorthSecurity/EyeWitness#423]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Linux

## Pastebin link to error you are encountering
https://pastebin.com/NKJCguuA

## Expected behavior (vs. what you encountered)
I am not seeing any results on the scanner, and getting the error as seen in the pastebin.

**Comment by ChrisTruncer** [comment]
I'm going to close this because this is ideally fixed in the latest version of EyeWitness. Please pull down the latest updates, run the setup script, and let me know if you encounter any issues.
