### ISSUE TITLE
Errors/warnings when building docker container

### ISSUE THREAD

**Issue by cyberfreaq** [FortyNorthSecurity/EyeWitness#425]
## OS Used - ALL Information (architecture, linux flavor, etc.)
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.4
Codename:	kali-rolling

## Pastebin link to error you are encountering
https://pastebin.com/99YnWfFF

## Expected behavior (vs. what you encountered)
When building docker images, multiple errors/warnings are shown:

```
TERM environment variable not set.
[... snipped ...]
E: Unable to locate package firefox-esr
[... snipped ...]
/usr/bin/python3: No module named pip
/usr/bin/python3: No module named pip
[... snipped ...]
```

**Comment by ChrisTruncer** [comment]
I would imagine that the system has python 3 installed, but this might be a question better left for @netanelravid because he did the hard work of building the docker image. I'll let him chime in.

**Comment by ChrisTruncer** [comment]
This should now be fixed, thanks!
