### ISSUE TITLE
Not completing scans due to exceptions

### ISSUE THREAD

**Issue by Raikia** [FortyNorthSecurity/EyeWitness#429]
![img](https://i.imgur.com/24h2xO8.png)

I ran EyeWitness against a list of approximately 528 systems that all have at least port 80 or 443 open and it took a screenshot of 5 of them and then quit.  I'm thinking it might be related to #428 where one thread throws an exception and exits prematurely?

If so, you should add error handling so worst case if an exception is thrown, the entire data set isn't just skipped over and only that host has an error.

**Comment by ChrisTruncer** [comment]
Is there any chance you can send the list of systems over so I can test against that? It'll help me narrow down the bug against since it would be repeatable for me.

**Comment by Raikia** [comment]
I'll twitter message one to you

**Comment by ChrisTruncer** [comment]
This should also now be fixed, so this is being closed.
