### ISSUE TITLE
Feature Request: Option to define additional ports to look for in xml file

### ISSUE THREAD

**Issue by z0kk** [FortyNorthSecurity/EyeWitness#431]
**Feature Request**

It would be nice if EyeWitness's `-x` option took screen shots on non-standard ports defined by the user. For example, being able to specify (perhaps in a config file) that if ports 4343, 9443, etc are in the Nmap file, scan them with https; if ports 9080, 8090, etc are found, scan them with http, and so on.

Right now I have a little script to build URLs from Nmap output, and then just feed them into EyeWitness, but it would be kind of cool if EyeWitness had a built-in way to do it.

**Comment by ChrisTruncer** [comment]
EyeWItness does already do this. If you perform service detection with your nmap scan, even if the web server is on a non-standard port Eyewitness will parse the xml and take a screenshot of it (assuming NMap or Nessus detect that port as a web server)

**Comment by z0kk** [comment]
Excellent, thanks for the info!
