### ISSUE TITLE
Not possible to use Eyewitness via a socks5 proxy

### ISSUE THREAD

**Issue by nbeguier** [FortyNorthSecurity/EyeWitness#436]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Debian 9.8

## Pastebin link to error you are encountering
```
EyeWitness.py: error: unrecognized arguments: --proxy-ip 127.0.0.1 --proxy-port XXXX --proxy-type socks5
```

## Expected behavior (vs. what you encountered)
Since my last pull (I'm on HEAD now) these options have disapeared. Before, it was possible to take screenshot via a socks5 proxy...

**Comment by ChrisTruncer** [comment]
Yes, that's correct. At the moment, it doesn't support it. However, if you are interested in sending a pull request in, I would be happy to review it

**Comment by nbeguier** [comment]
With pleasure, I would be happy to contribute to this project ;)

**Comment by ChrisTruncer** [comment]
Closing this due to it now being merged. Thanks!
