### ISSUE TITLE
This script doesnt work

### ISSUE THREAD

**Issue by PauloChoupina** [FortyNorthSecurity/EyeWitness#438]
I tried everything.

First i tried to setup with setup.sh
Ubuntu, debian and kali.

The script wont take a printscreen of google, just timesout.. locally and in a vps

Then I tried to use docker, i got this:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown.

I tried so search for a solution here: 
https://github.com/kubernetes/minikube/issues/4423

tried their dockerfile, i got this:
COPY failed: stat /var/lib/docker/tmp/docker-builder247982902/target/dependency/BOOT-INF/lib: no such file or directory

i still tried to do: docker run eyewitness
same error:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown.

I even tried deleting the copy line in that dockerfile, i dont get the error anymore (genious ha? xD) but then i get the same: 
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown.

In ubuntu, debian and kali.

Can you guys help me please?

**Comment by digininja** [comment]
Go back to Kali, Ubuntu or Debian, install it, run it, and then explain what happens, how it fails and any errors it gives.

If it is that it times out, show that you can access the site from the same box where the timeout occurs with both curl and wget.

**Comment by PauloChoupina** [comment]
I tried ubuntu again, i did the install and i changed the Dockerfile in the last line:
ENTRYPOINT ["python", "EyeWitness.py", "-d", "/tmp/EyeWitness/results", "--no-prompt"]

i make it like this:
ENTRYPOINT ["python3", "EyeWitness.py", "-d", "/tmp/EyeWitness/results", "--no-prompt"]

**Comment by PauloChoupina** [comment]
root@ubuntu-s-1vcpu-1gb-nyc3-01:~/EyeWitness# docker run eyewitness
Traceback (most recent call last):
  File "EyeWitness.py", line 13, in <module>
    from modules import db_manager
  File "/home/root/EyeWitness/modules/db_manager.py", line 4, in <module>
    from modules.objects import HTTPTableObject
  File "/home/root/EyeWitness/modules/objects.py", line 5, in <module>
    from modules.helpers import strip_nonalphanum
  File "/home/root/EyeWitness/modules/helpers.py", line 13, in <module>
    from netaddr import IPAddress
ImportError: No module named 'netaddr'

**Comment by PauloChoupina** [comment]
root@ubuntu-s-1vcpu-1gb-nyc3-01:~/EyeWitness# pip3 install netaddr
Requirement already satisfied: netaddr in /usr/local/lib/python3.6/dist-packages

**Comment by PauloChoupina** [comment]
still after that i get the same error

**Comment by ChrisTruncer** [comment]
Can you try the setup script please?

________________________________

**Comment by PauloChoupina** [comment]
ok 1 sec

**Comment by digininja** [comment]
Try it natively as well, rather than in Docker.

**Comment by PauloChoupina** [comment]
root@ubuntu-s-1vcpu-1gb-nyc3-01:~/EyeWitness# python3 EyeWitness.py --web --single google.com

###############################################################################
#                                  EyeWitness                                  #
################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################

xdpyinfo was not found, X start can not be checked! Please install xdpyinfo!
Attempting to screenshot http://google.com
Message: Unable to find a matching set of capabilities

**Comment by PauloChoupina** [comment]
i get that

**Comment by digininja** [comment]
That package is from x11-utils, try installing that.

```
$ dpkg -S /usr/bin/xdpyinfo
x11-utils: /usr/bin/xdpyinfo
```

**Comment by PauloChoupina** [comment]
i did: sudo apt-get install x11-utils
and now from the command: python3 EyeWitness.py --web --single google.com

i get this: https://i.imgur.com/KcvDgDR.png

**Comment by PauloChoupina** [comment]
> That package is from x11-utils, try installing that.
> 
> ```
> $ dpkg -S /usr/bin/xdpyinfo
> x11-utils: /usr/bin/xdpyinfo
> ```

yeah i know

**Comment by PauloChoupina** [comment]
what can i do?

**Comment by PauloChoupina** [comment]
i used to use this tool i it used to work just fine, i don't know what happened

**Comment by digininja** [comment]
Must be a missing dependency as I've just checked the same command on an Ubuntu box and it works fine after running the setup script.

Did the script run OK with no errors?

![image](https://user-images.githubusercontent.com/117081/69011910-9daf1500-0967-11ea-88f6-80b94f7ed396.png)

**Comment by PauloChoupina** [comment]
https://pastebin.com/i1HLhC7G

and i get this:
E: Package 'firefox-esr' has no installation candidate

**Comment by PauloChoupina** [comment]
got it! 
apt-get install firefox 

this solved it
thanks guys

**Comment by digininja** [comment]
That's an Ubuntu box trying to install the Debian packages, can you post the output of this:

```
cat /etc/issue
```

**Comment by PauloChoupina** [comment]
Ubuntu 18.04.3 LTS \n \l

**Comment by PauloChoupina** [comment]
can you guys help me with something else?

I tired of keep tring xss payload after xss payload in some websites that got protection like filters and wafs, so i came up with the idea:
why not make a big list of payloads, insert them in the url and compile a list like: https://pastebin.com/urw1b5Su

then just run eyewitness i that file and check for the screenshots for results.

**Comment by PauloChoupina** [comment]
But

I got this: 

http.client.InvalidURL: URL can't contain control characters. '/index.php?id=en&info=1"><textarea autofocus onpointerenter=alert(1)>' (found at least ' ')


is there any way to fix this?

**Comment by digininja** [comment]
Odd, that should put you into the Ubuntu section of the setup script. I'll
have a look to see if I can spot why.

**Comment by digininja** [comment]
Make sure they are URL encoded in the file

**Comment by PauloChoupina** [comment]
ok i will try

**Comment by PauloChoupina** [comment]
It doesn't work i dont know why

**Comment by digininja** [comment]
Will let you debug that one

**Comment by digininja** [comment]
I just html encoded the space character in that URL you gave and it worked fine.

```
$ ./EyeWitness.py --web --single 'https://google.com/index.php?id=en&info=1"><textarea%20autofocus%20onpointerenter=alert(1)>'
```

**Comment by PauloChoupina** [comment]
yeah but i tried with the real vulnerable website and i dont get the alertbox that i get in the browser, instead i only get this: https://imgur.com/GnDvf1T

**Comment by digininja** [comment]
That shows EW is working and sending the requests.

Set up your own web server, make the request over http and then sniff the
traffic to compare EW and a browser.
