### ISSUE TITLE
WebDriver Error when trying to screenshot .onion sites

### ISSUE THREAD

**Issue by GrandAdmiralDan** [FortyNorthSecurity/EyeWitness#440]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali, latest release 2019.3
Firefox Quantum ESR 60.8.0esr (64-bit)

## Pastebin link to error you are encountering
pastebin.com/XCqB4KvW

## Expected behavior (vs. what you encountered)
I started with this blog: https://webbreacher.com/2017/09/02/dark-web-report-torghost-eyewitness-goodness/

I noticed that it includes the --headless command, but it looks like that's no longer supported? What's covered in the blog is what I'm trying to accomplish. 

## Any additional information
Screen shots using Eyewitness for normal .com websites while connected over Tor work completely fine. 

The address for The Guardian's .onion site is 33y6fjyhs3phzfjj.onion  so I was using that as an example. I can navigate to it without any issues with the Tor service running on Kali and utilizing Firefox as a browser. 

I saw previous posts stating Eyewitness won't work over SOCKS proxy, but it's taking a screenshot of .com and such websites over the same proxy without any issues. These posts were also dated a couple years back, too. 

I've verified I can navigate to .onion sites without any issues. What I'm executing for a command is as follows `./Eyewitness.py --web --timeout 60 --single 33y6fjyhs3phzfjj.onion`

I get the WebDriver Error about 3-4 seconds into the script running.

**Comment by digininja** [comment]
You would need to be able to point EyeWitness at a SOCKS proxy to be able
to screenshot over Tor but due to the upgrade to Python 3, there is
currently no SOCKS support.

You could try going back to an earlier version using Python 2 which had
SOCKS support and try that.

**Comment by GrandAdmiralDan** [comment]
That did it! I downloaded V 2.2.3 and then ran the following command:
`./Eyewitness.py --web --timeout 60 -f links.txt --proxy-ip 127.0.0.1 --proxy-port 9050 --proxy-type socks5`

Thanks a bunch!

**Comment by digininja** [comment]
No problem, remember to close the issue.

**Comment by alihadi890** [comment]
Hello,

Please can you detail the steps for this fix. I have tried to roll back to v 2.2.3 and I'm always getting RDP libraries not found (I already went the issue and tried all the fixes and still not working).

Thanks in advanced.
