### ISSUE TITLE
Urlparse module error

### ISSUE THREAD

**Issue by terencemartin** [FortyNorthSecurity/EyeWitness#443]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali 2019.4

## Error message

Traceback (most recent call last):
  File "/opt/EyeWitness/EyeWitness.py", line 13, in <module>
    from modules import db_manager
  File "/opt/EyeWitness/modules/db_manager.py", line 4, in <module>
    from modules.objects import HTTPTableObject
  File "/opt/EyeWitness/modules/objects.py", line 5, in <module>
    from modules.helpers import strip_nonalphanum
  File "/opt/EyeWitness/modules/helpers.py", line 15, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

## Expected behavior (vs. what you encountered)
I am unable to get the script to work after the last update. I get the above error even after running the setup,sh script.

**Comment by ChrisTruncer** [comment]
urllib should be standard with python3 (unless I am wrong). It's installed on my kali VM when I just tested it.

<img width="579" alt="urllibtest" src="https://user-images.githubusercontent.com/1674822/70273179-d1ab7800-1766-11ea-9452-9e0fd3157a57.png">

**Comment by terencemartin** [comment]
Chris, 

It appears that reinstalling python3 fixed the issues. Thank you,

Terence
