### ISSUE TITLE
Message: invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by Naategh** [FortyNorthSecurity/EyeWitness#445]
When I'm trying to run the script via the following command it's giving me an error:
`python EyeWitness.py -f list.txt --web --no-prompt -d test`

Error:
`
Message: invalid argument: can't kill an exited process
`

**Comment by ChrisTruncer** [comment]
You are using python 2 to start with, EyeWitness uses Python 3.

Please be sure to look at the readme and the many guides on how to use it.

Hope that helps!

________________________________

**Comment by Naategh** [comment]
No, I'm using Python 3.7.5

**Comment by ChrisTruncer** [comment]
Your example is you running it with Python 2, not 3.

Try just calling the tool (./EyeWitness.py) with the options you need

**Comment by Naategh** [comment]
My default python is python3.
Also, that doesn't work!

**Comment by ChrisTruncer** [comment]
I just tested the exact command you provided on my Kali VM, and I did not have any issues with it. I received my report with everything in it. 

It looks like you deleted all the requested information when you create a Github issue, so I would need you to provide all of that information for me to be able to help troubleshoot this more.

**Comment by Naategh** [comment]
Hey I tested it on my VPS server and it works but on my local server doesn't work yet,
Also, I searched the error and it seems it's related to geckodriver but I couldn't fix it.
Anyway, Thanks for the help I'll close this issue.

**Comment by joswr1ght** [comment]
Adding here in case someone else received this error message; `geckodriver` won't run as root with modern Firefox. Don't run EyeWitness as root. 🤷‍♂️
