### ISSUE TITLE
Encountered "TypeError: unsupported operand type(s)" while running EyeWitness

### ISSUE THREAD

**Issue by str4n63r** [FortyNorthSecurity/EyeWitness#446]
## Error Details: Encountered following error while running EyeWitness on multiple occasions

Traceback (most recent call last):
  File "./EyeWitness.py", line 484, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 385, in multi_mode
    ua_dict = get_ua_values(cli_parsed.cycle)
  File "/root/Desktop/t00ls/EyeWitness/modules/helpers.py", line 560, in get_ua_values
    + crawler_uagents.items() +
TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'

**Comment by ChrisTruncer** [comment]
There's a couple things here to discuss. First, you're specifying a user-agent to use, but then also telling it to cycle user agents. So EyeWitness is receiving two conflicting options, I would take one of them out. Once I ran the --user-agent option without the --cycle, it worked.

With that said, there is an error when using the --cycle option, I'm going to check into that now.

**Comment by ChrisTruncer** [comment]
At this point, I don't think I am going to plan on supporting the cycle option. I like having the ability to set the user-agent manually, but I've never had the use of it come up (and it's always a nightmare to support). For the time going forward, I would say the best option is the --user-agent option!
