### ISSUE TITLE
Feature Request: Ability to send custom headers

### ISSUE THREAD

**Issue by geeknik** [FortyNorthSecurity/EyeWitness#452]
Hi, thanks for making such a great tool. Would it be possible to add the ability to send a custom header with each request by providing a file that contains said headers?

```
URL|X-Header-Name: foo
URL|X-Foo: name
etc|etc: etc
```
Of course you could use whatever delimiter makes the most sense.  Thank you.

**Comment by whoismikem** [comment]
Selenium webdriver that this project uses makes implementing this tricky.

**Comment by geeknik** [comment]
No worries, we ended up just running a proxy server to handle injecting headers.
