### ISSUE TITLE
Add more Security vulnerabilities -- flask jinja2 ssti / flask pin

### ISSUE THREAD

**Issue by 99Kies** [FortyNorthSecurity/EyeWitness#457]
Add more Security vulnerabilities -- flask jinja2 ssti / flask pin

**Comment by ChrisTruncer** [comment]
We never have added vulnerabilities to this tool. I am open to it, but I would love to see it in a pull request because this hasn't been the original focus of EyeWitness. But feel free to open a PR with this capability

**Comment by digininja** [comment]
@99Kies  If you are going to work on it, the easiest way would probably be to add an extra text field that could be used for notes, that way you could add a note comment to say "look for ssti" or something like that.
