### ISSUE TITLE
After Installation Errors

### ISSUE THREAD

**Issue by oghenejivwe** [FortyNorthSecurity/EyeWitness#459]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

## Pastebin link to error you are encountering
./EyeWitness.py --help

## what you encountered

  File "./EyeWitness.py", line 13, in <module>
    from modules import db_manager
  File "/root/EyeWitness/modules/db_manager.py", line 2, in <module>
    import sqlite3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by ChrisTruncer** [comment]
Are you using the latest version of EyeWitness and Kali? I just installed EyeWitness on Kali to test this and it is running without any issues. Did you run the setup script?

**Comment by oghenejivwe** [comment]
Thanks. I just updated my Kali and it worked perfectly.
