### ISSUE TITLE
Hit Timeout Received By EyeWitness

### ISSUE THREAD

**Issue by deFr0ggy** [FortyNorthSecurity/EyeWitness#463]
I am using Kali Linux 2020.1 in VirtualBox - fully updated and upgraded. While using the EyeWitness and passing it a file with a bunch of random URLs i am getting Hit Timeout Limit error and the screenshot is not being taken by the EyeWitness (Screenshots Attached). 

Meanwhile i also tried to pass a single domain and am having the same issue as well. 

I tried "--show-selenium" and found that the domains are loading in the browser pretty fine and their main page is also loading but the EyeWitness is giving Hit Timeout here as well. 

I am not sure about the reason so would like to have a help in this regard. I have also tried reinstalling the EyeWitness and it's dependencies but it is actually not working. 

The commands i have been using are as above. 

```
1. eyewitness -f domains.txt --prepend-https --resolve -d Report 
2. eyewitness --show-selenium --single google.com -d google
```
![alt_text](https://i.imgur.com/FELndnK.png)

**Comment by ChrisTruncer** [comment]
Did you install via the setup script, or apt? Can you try making a textfile with just the following in it

https://www.google.com
https://www.gmail.com

And then try running it with "./EyeWitness.py -f urls.txt"

**Comment by deFr0ggy** [comment]
I have installed it via "apt". I have tried doing your way and it doesn't seems to work! 
![2020-03-20 12_45_55-Kali-Linux-2020 1-vbox-amd64  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/16836050/77200939-d5aa9e00-6aa8-11ea-9478-def74acb2e4b.png)

**Comment by digininja** [comment]
I'd run it through a proxy and see what is happening.

**Comment by deFr0ggy** [comment]
I  have tried installing it via the script as well - tried using the proxy as well but the issues seems to be still there!

**Comment by digininja** [comment]
By proxy, I meant something like Burp so you could see the requests to see
if they were working or timing out

**Comment by ChrisTruncer** [comment]
unfortunately it might be easiest to verify this on a clean VM if you could set one up. All should be working if you install via cloning from git then running the setup script. I don't maintain apt packages, and they tend to fall behind releases, so I have no idea what version or anything you are on

**Comment by deFr0ggy** [comment]
Chris i have also tried installing it via the script on the Kali VM but let me create a sample Ubuntu VM to test this issue. I will be back on this!

**Comment by ChrisTruncer** [comment]
please only install on your new vm by cloning from git and running the setup script

**Comment by ChrisTruncer** [comment]
Just checking in on this since it has been a bit because I can't seem to recreate the issue

**Comment by deFr0ggy** [comment]
Hi Chris, 

Kindly close the issue. I tried it on my new Kali setup and it worked fine. I don't know what the issue was. It wasn't working before and i just tested it and it seems to work fine. 

I had a question that sometimes EyeWitness is not able to take the screenshot even when there is an application running over a domin. It does this with few domains and takes the screenshots of others pretty fine. Thanks
