### ISSUE TITLE
[*] ERROR: Web page possibly blank or SSL error!

### ISSUE THREAD

**Issue by Nikhil15292** [FortyNorthSecurity/EyeWitness#466]
when i try Eyewitness in powershell facing error

Attempting to capture: http://ca.indeed.com  (1/869)
[*] ERROR: Web page possibly blank or SSL error!

**Comment by ChrisTruncer** [comment]
You're not providing any information that we can use to help debug this. I tested loading the site and it worked on my end. Again, this is not a PowerShell script.

<img width="821" alt="successfulrun" src="https://user-images.githubusercontent.com/1674822/78174334-5016de80-7416-11ea-8308-c19cc311841c.png">

**Comment by Nikhil15292** [comment]
![2020-04-02 00_54_15-C__Windows_System32_cmd exe](https://user-images.githubusercontent.com/53235062/78177963-8c7d2580-747c-11ea-8365-861103088526.png)
