### ISSUE TITLE
Getting Error in cmd 

### ISSUE THREAD

**Issue by Nikhil15292** [FortyNorthSecurity/EyeWitness#467]
![2020-04-02 00_54_15-C__Windows_System32_cmd exe](https://user-images.githubusercontent.com/53235062/78178150-d239ee00-747c-11ea-88be-cbbf8793fd9a.png)

**Comment by ChrisTruncer** [comment]
You are showing the output from Python with the Windows binary. You are mixing the two up. Please read the README

**Comment by Nikhil15292** [comment]
Please check command written in last line that is .exe not .py i downloaded from authorized site only given in readme
