### ISSUE TITLE
not able to execute --all-protocols 

### ISSUE THREAD

**Issue by manisashank** [FortyNorthSecurity/EyeWitness#477]
## OS Used - ALL Information (architecture, linux flavor, etc.)
VERSION="2020.2"
VERSION_ID="2020.2"
VERSION_CODENAME="kali-rolling"

## Pastebin link to error you are encountering
https://pastebin.com/x6VxxBen

**Comment by ChrisTruncer** [comment]
That's because that isn't an option for the tool, so you're giving it a non-existent flag. That flag was removed months ago when upgrading to python 3.
