### ISSUE TITLE
Huge geckodriver.log file

### ISSUE THREAD

**Issue by xqd-ai** [FortyNorthSecurity/EyeWitness#478]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali latest

## Pastebin link to error you are encountering
N/A

## Expected behavior (vs. what you encountered)
Turn off geckodriver file!

## Any additional information
I'm getting a very huge geckodriver.log file with every use of EyeWitness, file size is tens of gigabytes, is there a way to turn off this log

**Comment by ChrisTruncer** [comment]
I'm not sure how you're getting it that size, but EyeWitness itself doesn't generate geckodriver.log. That will be Selenium.

We did just merge in a pull request to specify the location for the geckodriver.log file. You can just point it to /dev/null or some other location if you want to at this point

**Comment by xqd-ai** [comment]
Thanks! that solved the problem, and I also found the reason for the huge geckodriver.log file (22GB), it was because of the old firefox-esr version (68) which was generating a lot for errors and warnings, so the issue solved after updating firefox to the latest version
