### ISSUE TITLE
consuming ALL ram

### ISSUE THREAD

**Issue by marcelo321** [FortyNorthSecurity/EyeWitness#484]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Linux ubuntu.

After using Eyewithness and not using it anymore i see all of my 8gb rams used by firefox proccesses, this happened like 3 times and i had to reboot the server.

I had like x10 of this
![imagen](https://user-images.githubusercontent.com/29487296/84084693-4f706a80-a9ba-11ea-842e-376418ed7287.png)

`killall firefox` doesn't appear to work, but something isn't working as expected here... once the program is not running it should stop using ALL ram.

**Comment by JawadHussainC** [comment]
same here

**Comment by ChrisTruncer** [comment]
The best bet for this would be to minimize the number of threads running in parallel, I run this on a VM with far less resources and have yet to have this be a problem
