### ISSUE TITLE
permission denied screens

### ISSUE THREAD

**Issue by njmulsqb** [FortyNorthSecurity/EyeWitness#485]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Kali Linux 2020.2
################################################################################
#                                  EyeWitness                                  #
################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################

Directory Exists! Do you want to overwrite? [y/n] y
Traceback (most recent call last):
  File "/usr/share/eyewitness/EyeWitness.py", line 382, in <module>
    cli_parsed = create_cli_parser()
  File "/usr/share/eyewitness/EyeWitness.py", line 170, in create_cli_parser
    shutil.rmtree(args.d)
  File "/usr/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.8/shutil.py", line 656, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 654, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'screens'

## Expected behavior (vs. what you encountered)
Sorry pastebin wasnt working so I pasted here.. I am expecting eyewitness to work normally, but its giving me error again and again. I tried everything from reinstalling to trying git clone version and apt version.

**Comment by Aaryan9898** [comment]
Run in superuser mode

**Comment by ChrisTruncer** [comment]
Can you run it as a normal user, and install on a clean system? Only the setup script will require sudo.

**Comment by 0xVIC** [comment]
Run from a folder with normal privs.
For example: python3 /opt/EyeWitness/Python/EyeWitness.py --web -f hosts.txt

**Comment by IGzer26** [comment]
I have one very big and critical issue on this tool. I have the same option "Directory Exists! Do you want to overwrite? [y/n]" first i entered n but nothing happend but after that i tried to give y and my some files are deleted and replaced with some js css and bash file . I lose my important data cause of this tool. Now tell me what i do ?

**Comment by IGzer26** [comment]
I think this tool have overwrite virus.

**Comment by digininja** [comment]
As a security professional I always do a code review of any open source
tool before using it, didn't you do the same?
