### ISSUE TITLE
Selinum not found for the Docker module

### ISSUE THREAD

**Issue by kvsaurav** [FortyNorthSecurity/EyeWitness#489]
:~/github/EyeWitness/Python/setup$ sudo docker run \
>  --rm \
>     -it \
>     -v ~/EyeWitness:/tmp/EyeWitness \
>     eyewitness \
>     --web \
>     --single http://www.google.com
[*] Selenium not found.
[*] Please run the script in the setup directory!

**Comment by ChrisTruncer** [comment]
I unfortunately don't support the docker image, and it looks to be an old version of EyeWitness. I would recommend to just run it on a VM
