### ISSUE TITLE
Dies with encoding exception

### ISSUE THREAD

**Issue by s3c** [FortyNorthSecurity/EyeWitness#490]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Debian Linux - Buster

## Expected behavior (vs. what you encountered)

Expect program to finish, dies with exception below.

## Any additional information

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "./EyeWitness.py", line 284, in worker_thread
    cli_parsed, http_object, driver)
  File "/home/user/Apps/EyeWitness/Python/modules/selenium_module.py", line 273, in capture_host
    http_object.source_code = driver.page_source.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by ChrisTruncer** [comment]
can you provide the URL that was causing this error?

**Comment by s3c** [comment]
Afraid not, was doing a sweep across maybe 30k internal hosts. Did a workaround to just catch AttributeError and print an error message, which seems to work fine.

**Comment by ChrisTruncer** [comment]
For the meantime then, I am planning on leaving this in here. I don't want to just do a catch for it because I want to get a URL where this consistently happens and build a proper exception for it.

Thanks for submitting this, and in you can reproduce this with a URL please submit it to me and I'll look to build this out.

**Comment by barrett092** [comment]
Getting the same error.
