### ISSUE TITLE
Recursive symlink /usr/sbin/geckodriver -> /usr/sbin/geckodriver (arch-linux)

### ISSUE THREAD

**Issue by cuvidk** [FortyNorthSecurity/EyeWitness#499]
## OS Used - ALL Information (architecture, linux flavor, etc.)
output for `uname -r`: 5.8.3-arch1-1

## Pastebin link to error you are encountering
https://pastebin.com/c8zhsCFf

## Expected behavior (vs. what you encountered)
EyeWitness.py script works without errors and geckodriver actually gets installed.

## Any additional information
The problem comes from the setup.sh script. Arch linux dropped the distinction between `/usr/sbin` and `/usr/bin`, and by that I mean the `/usr/sbin` is a symlink to `/usr/bin`. When installing the geckodriver, setup.sh does the following:
```bash
    if [ ${MACHINE_TYPE} == 'x86_64' ]; then
      wget ${geckodriver_x86_64}
      tar -xvf geckodriver-v0.26.0-linux64.tar.gz
      rm geckodriver-v0.26.0-linux64.tar.gz
      mv geckodriver /usr/sbin
      if [ -e /usr/bin/geckodriver ]
      then
      	rm /usr/bin/geckodriver
      fi
      ln -s /usr/sbin/geckodriver /usr/bin/geckodriver
    else
...
```
It's extracting the archive, then moves the geckodriver binary in `/usr/sbin` which as stated above points to `/usr/bin`. After that it proceeds to remove `/usr/bin/geckodriver` if it exists. So it ends up removing the binary that it just moved. It then creates the symlink `/usr/bin/geckodriver` which points to `/usr/sbin/geckodriver`. However since` /usr/sbin` points to `/usr/bin` you end up with and infinitely recursive symlink and no geckodriver binary at all.

## Possible solution
Simply move the geckodriver binary in `/usr/bin` and drop the additional logic for Arch / Manjaro.

I can fix this if you guys want.

**Comment by ChrisTruncer** [comment]
same thing here - Please, feel free to submit a pull request with the updated setup script. We don't support arch, but have it in the setup script because other members of the community added support for it. If you want to update it, we're happy to merge it in.

**Comment by cuvidk** [comment]
https://github.com/FortyNorthSecurity/EyeWitness/pull/501
