### ISSUE TITLE
Bad package name python3-netaddr breaks the installation of the following package firefox (arch-linux)

### ISSUE THREAD

**Issue by cuvidk** [FortyNorthSecurity/EyeWitness#500]
## OS Used - ALL Information (architecture, linux flavor, etc.)
output for `uname -r`: 5.8.3-arch1-1

## Pastebin link to error you are encountering
https://pastebin.com/ZT1GZQ17

## Expected behavior (vs. what you encountered)
The EyeWitness.py script runs without errors and all required dependencies get installed.

## Any additional information
The following line in setup.sh under `Arch|Manjaro)` causes a broken installation:
```bash
pacman -S cmake python3 python-xvfbwrapper python-pip python3-netaddr firefox
```
The reason is that there's no module called `python3-netaddr` in arch. The actual package name is `python-netaddr` which installs the netaddr python3 module as can be checked here: https://www.archlinux.org/packages/community/any/python-netaddr/files/.

Furthermore, this bad package name stops `pacman` from installing the following packages, in this case firefox, resulting in the error provided in the pastebin above when running `EyeWitness.py`. As a solution for this I propose the following change for the `Arch|Manjaro)` case:
```bash
for pkg_name in cmake python3 python-xvfbwrapper python-pip python-netaddr firefox; do
    pacman -S --no-confirm "${pkg_name}"
done
```
In this way, in case a package failed to install from various reasons (like bad package name), the following packages will still be installed.

Tell me if you want me to make this change.

**Comment by ChrisTruncer** [comment]
Please, feel free to submit a pull request with the updated setup script. We don't support arch, but have it in the setup script because other members of the community added support for it. If you want to update it, we're happy to merge it in.

thanks!

**Comment by cuvidk** [comment]
Cool ! I think I need some permissions so I can push a branch with a fix.

**Comment by digininja** [comment]
You edit your fork and the submit a pull request which Chris then merges in
with master, you don't need any extra permissions for that.

**Comment by cuvidk** [comment]
ok, thanks

**Comment by cuvidk** [comment]
https://github.com/FortyNorthSecurity/EyeWitness/pull/501
