### ISSUE TITLE
Hit timeout limit when connecting....

### ISSUE THREAD

**Issue by njmulsqb** [FortyNorthSecurity/EyeWitness#509]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Parrot OS

## Pastebin link to error you are encountering

Starting Web Requests (9 Hosts)
Attempting to screenshot https://techontap.se
Attempting to screenshot https://secure.commissionunion.com
[*] Hit timeout limit when connecting to https://techontap.se, retrying
[*] Hit timeout limit when connecting to https://secure.commissionunion.com, retrying
Attempting to screenshot https://google.com
[*] Hit timeout limit when connecting to https://google.com, retrying
Attempting to screenshot https://facebook.com
[*] Hit timeout limit when connecting to https://techontap.se
[*] Hit timeout limit when connecting to https://facebook.com, retrying
Attempting to screenshot https://twitter.com
[*] Hit timeout limit when connecting to https://secure.commissionunion.com
Attempting to screenshot https://redtube.com
Attempting to screenshot http://techontap.se
[*] Hit timeout limit when connecting to https://google.com
[*] WebDriverError when connecting to https://mozilla.com
Attempting to screenshot http://microsoft.com
Attempting to screenshot http://microsoft.com
[*] Hit timeout limit when connecting to https://facebook.com
[*] Hit timeout limit when connecting to http://microsoft.com, retrying
[*] Hit timeout limit when connecting to http://microsoft.com
Finished in 104.94958281517029 seconds

[*] Done! Report written in the /home/najum98/Documents/MyTools/EyeWitness/Python/10062020_101247 folder!

## Expected behavior (vs. what you encountered)
No matter what I try, using --single or -f, using sudo or without sudo, using ./EyeWitness of Github or using apt package, the error is same, I have installed the ./setup.sh but after that if I run eyewitness it says command not found so I ran the already available EyeWitness.py in the directory but the issue is same. I cant have a VM, I want to run eyewitness on this OS.

**Comment by dumdumdugan** [comment]
Same issue and error occuring for me as well. 

OS: Ubuntu 18.04 LTS


Attempting to screenshot https://google.com
[*] Hit timeout limit when connecting to https://google.com, retrying
[*] Hit timeout limit when connecting to https://google.com

[*] Done! Report written in the /home/XXXXXX/Documents/EyeWitness folder!



No pics nor any other information other than a link to google.

**Comment by ChrisTruncer** [comment]
Sorry everyone, but without additional information I can't recreate this. I am able to test this and get it running on kali, debian, and ubuntu. Anything you can give us to help re-create it?

**Comment by fr33k3v1n0** [comment]
i have the same error on kali linux
