### ISSUE TITLE
not all screenshot are found in folder after the complete process

### ISSUE THREAD

**Issue by rasiras** [FortyNorthSecurity/EyeWitness#512]
## Expected behavior (vs. what you encountered)

i ran eyewitness against a list of 100 domains , it takes all and while the process is going on if i visit the folder i can see the screenshots, but once all the 100 are taken and process ends, and i visit the output folder i can only see some screenshots,
many of those screenshots i found on while the process was going on is not found at last

**Comment by ChrisTruncer** [comment]
Unfortunately, you did not provide any of the information we request when opening an issue. 

So my best guess is that if there are same images, you only see one instance of them. That is how the tool works. If the same image is present, we use one instance of it vs multiple. If you have any extra information though, feel free to open a new issue (but please provide all the requested info)
