### ISSUE TITLE
Where does EyeWitness gets installed?

### ISSUE THREAD

**Issue by FaizanNehal** [FortyNorthSecurity/EyeWitness#513]
I installed Eyewitness in my Kali Linux Machine according to the Installation guide provided, the installation was done successfully but where did it gets installed? I looked for it everywhere like in my root directory, home directory etc but I couldn't find it. Can you tell me how to run this thing once it is installed?

**Comment by mattgrandy** [comment]
There should be an "EyeWitness.py" file within the Eyewitness/Python directory that you downloaded from GitHub. You'll just run it with "./EyeWitness.py".
