### ISSUE TITLE
Not able to run Eyewitness in ubuntu 20.1LTS

### ISSUE THREAD

**Issue by h1hakz** [FortyNorthSecurity/EyeWitness#514]
###############################################################################
#                                  EyeWitness                                  #
################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################
Attempting to screenshot https://h1hakz.com
Message: Process unexpectedly closed with status 1
root@h1hakz-exp-lab:/home/h3hakz/tools/EyeWitness/Python# 

can any one help in this, i checked in another ubuntu machine also 16.4 but same issue.

**Comment by digininja** [comment]
There is no DNS record for that host so you won't get any screenshots for it.

If it is just an internal domain, what version of the app are you using and what command line arguments are you using?

**Comment by h1hakz** [comment]
Domain is public also the command and installation is same as mentioned in
the doc.

**Comment by ChrisTruncer** [comment]
Domain isn't public, agreed, so closing this issue
