### ISSUE TITLE
stack trace when -x is given a file that doesn't exist

### ISSUE THREAD

**Issue by digininja** [FortyNorthSecurity/EyeWitness#517]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali and latest Git pull

## Pastebin link to error you are encountering

Pass a filename that doesn't exist to -x and you get a stack trace.

https://pastebin.com/Wnx15Brx

## Expected behaviour (vs. what you encountered)

Handle the error in a nice, pretty, way.

## Any additional information

"Dreamt" is the only word in the English language that ends with "mt." - Don't know about American though, you could have made up any random spellings for things.

**Comment by ChrisTruncer** [comment]
just merged this in, thanks!
