### ISSUE TITLE
"process cannot access the file" if duplicate URL in file list in Windows app

### ISSUE THREAD

**Issue by digininja** [FortyNorthSecurity/EyeWitness#524]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Windows 10 using the .Net version of the app

## Pastebin link to error you are encountering

```
The process cannot access the file 'C:\Users\WoodR\AppData\Roaming\EyeWitness_2021-03-31_164253\src\http...site.txt' because it is being used by another process.
```

## Expected behaviour (vs. what you encountered)
no errors

## Any additional information
If there are duplicate URLs in the file list passed with `-f` you get the above error for all the duplicates.

**Comment by mattgrandy** [comment]
Fixed in https://github.com/FortyNorthSecurity/EyeWitness/commit/f7a8ce6f18c870ec4c4c1ed670e6c4ed14aae481
