### ISSUE TITLE
.Net app missing pagination at top of report

### ISSUE THREAD

**Issue by digininja** [FortyNorthSecurity/EyeWitness#525]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Win 10 .Net app

## Pastebin link to error you are encountering
n/a

## Expected behavior (vs. what you encountered)
Pagination at top and bottom of HTML report, it is only at the bottom

**Comment by mattgrandy** [comment]
Fixed in https://github.com/FortyNorthSecurity/EyeWitness/commit/f7a8ce6f18c870ec4c4c1ed670e6c4ed14aae481
