### ISSUE TITLE
No option to specify output directory in .Net app

### ISSUE THREAD

**Issue by digininja** [FortyNorthSecurity/EyeWitness#526]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Win 10 .Net app

## Pastebin link to error you are encountering
n/a

## Expected behavior (vs. what you encountered)
A command line option to be able to specify the output directory like you can in the Python version would be good.

**Comment by mattgrandy** [comment]
Fixed in https://github.com/FortyNorthSecurity/EyeWitness/commit/f7a8ce6f18c870ec4c4c1ed670e6c4ed14aae481
