### ISSUE TITLE
No module named html

### ISSUE THREAD

**Issue by ampf27** [FortyNorthSecurity/EyeWitness#528]
## OS Used - ALL Information (architecture, linux flavor, etc.)

kali 2020.4

## Pastebin link to error you are encountering

 have closed this issue but in the meantime another issue occured so to not open a new issue I have reopened this one.
I have tried the program but after the scan I got a error message related with HTML module missing it happens that it is installed. Can you take a look on this?

https://www65.zippyshare.com/v/91DlQlDC/file.html
(the error message)

Thank you

**Comment by mattgrandy** [comment]
Hey ampf27,

Would you be able to upload the screenshot/error code to GitHub?

Thanks

**Comment by ampf27** [comment]
I donn't know how to upload here however in this link https://www65.zippyshare.com/v/91DlQlDC/file.html   I have uploaded a screenshot of the error on kali 2020.4.
