### ISSUE TITLE
Scan getting stuck on site that uses digest authentication

### ISSUE THREAD

**Issue by denevin** [FortyNorthSecurity/EyeWitness#531]
I'm running eyewitness with default parameters against a nessus scan.
Out of 600 web hosts one host kept on getting stuck and not timing out.
Manually cancelling and resuming the scan didn't fix the issue, changing timeout options didn't fix it either.
After manually browsing to the website with a web browser and capturing the response, the problematic host is using digest authentication. See http messages below.

## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Rolling

#### Request
GET / HTTP/1.1
Host: 192.168.1.5
User-Agent: Mozilla/5.0 [removed]
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: close
Upgrade-Insecure-Requests: 1

#### Response
HTTP/1.1 401 Unauthorized
Server: Microsoft-IIS
WWW-Authenticate: Digest qop="auth",algorithm=MD5-sess,nonce="+Upgraded+[removed]",charset=utf-8,realm="Digest"
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
Date: <snip>
Connection: close
Content-Length: 0

## Expected behavior (vs. what you encountered)
It would be great if you could add logic to the application to skip the sites that require digest authentication until it's supported, since in order for the scan to complete and for the report to generate, I had to run this query "select * from http where complete = 0' on the 'ew.db' sqlite database and manually delete the host that uses digest auth from the database.

**Comment by denevin** [comment]
Oops, sorry I missed that it was digest auth, I just updated the issue description.

**Comment by ChrisTruncer** [comment]
Closing for now, if @denevin can post a public URL that we can test against, we can look into it, but it would more likely be a library issue (however like @digininja said, everything should be able to handle that).
