### ISSUE TITLE
Why this exe is showing it as virus?

### ISSUE THREAD

**Issue by crazywifi** [FortyNorthSecurity/EyeWitness#534]
When I am downloading the eyewitness.exe file, it's showing me as Trojan:Win32/AgentTesla!ml. Why?

**Comment by ChrisTruncer** [comment]
Because antivirus is notoriously bad at actually classifying true threats.

If you don't feel comfortable running the compiled version, you're free to take the source and compile it yourself for use.

**Comment by crazywifi** [comment]
Thanks for the update :) BDW your tool is best. I love it.
