### ISSUE TITLE
Failed to parse: http://127.0.0.1:XXXX won't scan

### ISSUE THREAD

**Issue by StefanTobler** [FortyNorthSecurity/EyeWitness#540]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Parrot OS 4.11

## Expected behavior (vs. what you encountered)

![image](https://user-images.githubusercontent.com/22108632/133499209-8d81235f-7417-41c8-8c8f-79e17fa6a32a.png)

Every time I try to SS domains it does not even look at the domains in my file, it just tries to connect to the local host? 

## Any additional information

I have tried uninstalling and reinstalling. I have also tried putting only one domain in the domain file that I know exists.

**Comment by ChrisTruncer** [comment]
Are you trying to use this through a proxy? Do you have a web server running locally on all of those ports?

**Comment by StefanTobler** [comment]
No proxy settings, and no webserver running on those ports. Could running it in a VM be a problem?

**Comment by ChrisTruncer** [comment]
Then either the parsing is off, or there is something wrong with the input list that you are giving it, because EyeWitness is just trying to hit stuff on your local system. If you want, feel free to share the URL list.

**Comment by StefanTobler** [comment]
![image](https://user-images.githubusercontent.com/22108632/133500998-eb0ce803-d6b5-43bd-8920-4722dc411ae0.png)

**Comment by StefanTobler** [comment]
Here is a snippet of the URL list

**Comment by ChrisTruncer** [comment]
I would need you to paste it as text, with that said, there should be no problem with parsing this and running it.

**Comment by StefanTobler** [comment]
Sorry about that, I'm not logged into GH on the VM. Another list I tried and got the same result with was my personal website.

https://stefantobler.com

**Comment by ChrisTruncer** [comment]
I unfortunately can't re-create this in any way on my system. I'm not sure if you have a system wide proxy setting that's trying to force all requests through it, but I am able to provide a list of urls, run EyeWitness, and get the results. Now, you don't need the --webS flag there to run, not sure where you saw that. But I just verified a run on my system, and I've never seen a report like this before, so I think it might be something tied to your VM/system.

**Comment by StefanTobler** [comment]
Strange, thanks for the quick feedback. 

I accidentally typed the `S` when taking the screenshot. I was using the `--web` flag.

I will close this issue and continue to troubleshoot.
