### ISSUE TITLE
redhat-release file doesn't exist on non-Redhat boxes

### ISSUE THREAD

**Issue by digininja** [FortyNorthSecurity/EyeWitness#563]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali

## Pastebin link to error you are encountering

The setup script tries to read the redhat-releases file which doesn't exist on non-Redhat boxes so it throws an error. It doesn't affect the script, but it isn't pretty.

```
#######################################################################
#                          EyeWitness Setup                           #
#######################################################################

cat: /etc/redhat-release: No such file or directory
cat: /etc/redhat-release: No such file or directory
0% [Working]

```

## Expected behaviour (vs. what you encountered)
It should be pretty and not show errors.

**Comment by digininja** [comment]
Check https://github.com/FortyNorthSecurity/EyeWitness/pull/564

**Comment by ChrisTruncer** [comment]
this is merged in, thanks!
