### ISSUE TITLE
File Not Found - webdriver_prefs.json

### ISSUE THREAD

**Issue by T4c03num** [FortyNorthSecurity/EyeWitness#587]
OS Used - Kali 5.19.0

Error I receive when running  python3 EyeWitness.py --single www.google.com

################################################################################
#                                  EyeWitness                                  #
################################################################################
#           FortyNorth Security - https://www.fortynorthsecurity.com           #
################################################################################

Attempting to screenshot http://www.google.com
Traceback (most recent call last):
  File "/home/someone/EyeWitness/Python/EyeWitness.py", line 408, in <module>
    single_mode(cli_parsed)
  File "/home/someone/EyeWitness/Python/EyeWitness.py", line 228, in single_mode
    driver = create_driver(cli_parsed)
  File "/home/someone/EyeWitness/Python/modules/selenium_module.py", line 39, in create_driver
    profile = webdriver.FirefoxProfile()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/firefox_profile.py", line 61, in __init__
    with open(os.path.join(os.path.dirname(__file__),
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver_prefs.json'

I am also running into the same error message via the apt installed version. Completely removed the apt package with no avail. Tested eyewitness on 4 machines so far all with the same error. I also tried to populate the webdriver_prefs.json with a random one I found on github for Firefox but it just threw a unexpected error. A couple of teammates are having issues as well who are running separate versions of kali.

**Comment by Relkci** [comment]
What version of python 3 are you using?

**Comment by T4c03num** [comment]
Python 3.10.8

**Comment by Relkci** [comment]
I initially saw the same issue.  on 3.10.7 
Looking into it.  I also manually added the webderver_prefs.json from another host and was able to bypass the issue.  Did this work for you?

Possibly a change in an upstream selenium update that doesn't include it.

**Comment by 0x6d6f7468** [comment]
Just checked, didn't see any issues reported in the Selenium repo about the issue.

I also installed EyeWitness on five Kali implants with Python 3.10.7 earlier today and it ran without issue. Wondering what's different between @Relkci's instance and mine...

**Comment by T4c03num** [comment]
When I first wrote this I did try and put the following json file in the location.

https://raw.githubusercontent.com/zh217/better-firefox-driver/master/resources/org/openqa/selenium/firefox/webdriver_prefs.json

It didn't work initially but I just tried again and I am in business. Not sure what happened there, possible PEBKAC. But I am in business now with the above webdriver_prefs.json

**Comment by 0x6d6f7468** [comment]
Glad to hear you got it working. A bit of a kludge, but it'll get you there for now. Am curious to see if you have the same issue on another computer/VM.

**Comment by T4c03num** [comment]
That's what made me spin up the issue. I have other VM's both at work and personal and they are all having this issue right now. I just checked 3 work machines and they are running 3.10.8 as well. Going to implement the fix on those now.

**Comment by T4c03num** [comment]
Good Morning! 

So I was not crazy yesterday. When I went to implement the fix on some of my work machines I ran into a "geckodriver unexpectedly exited status code 64". 

What I found that worked for me was downloading the gecko driver tar from here: https://github.com/mozilla/geckodriver/releases 

Then I essentially followed the setup.sh script yall have and did the following:

tar -xvf geckodriver-v0.32.0-linux64.tar.gz
rm geckodriver-v0.32.0-linux64.tar.gz
mv geckodriver /usr/sbin
rm /usr/bin/geckodriver (I had a old one I guess)
ln -s /usr/sbin/geckodriver /usr/bin/geckodriver

Once I did all of that I was back in business on my other machines.

**Comment by ChrisTruncer** [comment]
That's interesting to learn. I've seen EyeWitness display errors at times when it does have an old version of the geckodriver, but it's a different error. Anytime I receive a bug report with that error, I know it means we need to add the latest geckodriver to the setup script. Looks like I need to add this one to the list.

Thanks for investigating this and reporting what worked.
